### PR TITLE
[ AnimeCore ] Frontend : Add in `TrendingHero`

### PR DESCRIPTION
**Pull request by baseplate-admin**
#115

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@AKindWorld 

image

**Comment by baseplate-admin** [comment]
For now we are targetting mobile only with the 2nd layout

**Comment by baseplate-admin** [comment]
@AKindWorld Final iteration 🗡️ 

image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
At this point this is half responsive :) 

Meaning if you run the site on desktop mode and then switch to mobile its not gonna work :\

```svelte
   <Swiper
            slidesPerView={$responsiveMode === "mobile" ? 3 : 1}
            on:swiper={onTrendingSwiper}
            pagination={{
                el: ".trending__pagination__element"
            }}
            modules={$responsiveMode === "mobile" ? [] : [EffectFade, Pagination]}
            effect={$responsiveMode === "mobile" ? "slide" : "fade"}
        >
            {#each Array(11) as _, i}
                <SwiperSlide>
                    <TrendingHero
                        slideNumber={String(i).padStart(2, "0")}
                        on:backClick={onTrendingSwiperBackward}
                        on:forwardClick={onTrendingSwiperForward}
                    />
                </SwiperSlide>
            {/each}
        </Swiper>
```

This code is not listening to event and i dont know what to do :\

**Comment by AKindWorld** [comment]
This looks pretty amazing! Great work @baseplate-admin!

I'll update and check it locally and tell you the results, gimme a moment. Don't worry about the half-responsiveness since it's not all that much practical anyway.

But, all in all, this looks really amazing! :)

**Comment by baseplate-admin** [comment]
Okay i am making it ready for review

**Comment by baseplate-admin** [comment]
But make sure you test from the dev branch.. The V3 Branch is behind Dev branch

**Comment by AKindWorld** [comment]
Yup, just checked! It works amazingly both on desktop and mobile layouts.

Just 1 thing - and it isn't related to this - but, in the mobile layout, the top carousel should hide the next & previous buttons. That's all.

Really really amazing job though. This is a huge progress.

**Comment by baseplate-admin** [comment]
Yayyy.. Lemme fix the Top Carrousel.. Would you mind approving this PR?

**Comment by baseplate-admin** [comment]
@AKindWorld Looks good ?

image

**Comment by AKindWorld** [comment]
Sure sure! That looks all good now! I'll review and merge this PR! thanks a lot :)

Also, thanks hehe. I'm glad to be able to work on this xD

**Comment by baseplate-admin** [comment]
> Also, thanks hehe. I'm glad to be able to work on this xD

As am i 🗡️
 Meeting you has been one of the best thing that has happened to me because of programming :D

**Review by AKindWorld — APPROVED** [review]
alrightyyy! Huge amount of progress :)

**Comment by baseplate-admin** [comment]
Lets gooo !!!!

**Pull request merged**
