### PR TITLE
[ `Backend` ] : Replace `httpx` with `requests`

### LINKED ISSUE #334: [ `Backend` ] : Replace `HTTPX` with `requests`
So HTTPX is a new library and i decided to use it. But it doesnt have rate limiting. 

So for this reason i am planning to use python requests.

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@AKindWorld merge this

**Comment by baseplate-admin** [comment]
@AKindWorld Merge this please :D

**Comment by AKindWorld** [comment]
Hi! should I merge this now?

**Comment by baseplate-admin** [comment]
Go ahead

**Review by AKindWorld — APPROVED** [review]

**Pull request merged**
