### PR TITLE
[`Shinobi`] : Add `characters` parser

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
@sssuneeth

**Comment by sssuneeth** [comment]
Hey! Nice work
Can you send me the new openapi.json, any updates in it?

**Comment by baseplate-admin** [comment]
>  Can you send me the new openapi.json, any updates in it?

There's no update

**Pull request merged**
