### PR TITLE
[ `Backend` ] : Increase Code Quality

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@AKindWorld  i have modified the frontend a bit > Check if you can see any differences. 

This PR is good for merging

**Comment by baseplate-admin** [comment]
I am very proud of my python codes. But i am not so proud of my Javascript codes. Most of them are written in obscure patterns 💀

**Comment by AKindWorld** [comment]
Hi!

The frontend looks pretty good to me, although I didn't notice much differences (something under-the-hood?)

Is it possible to fix just some things though-
1. The scroll now feels much less snappier, like how do I explain it- scrolling amongst the various sections & anime list items feels a bit clunky and broken for some reason. Can this be improved by changing some CSS properties? I [took a look too](https://css-tricks.com/practical-css-scroll-snapping/), and Example 4 is what we're practically aiming for- smooth snapping. I'm not sure if this is possible though, or if it is a problem locked down by the JS. There's also another thing we can do, and that's to remove the scroll snap on all element except for the top carousel. Everything else can just be normal scroll - that way, we needn't worry about the slow snap. You can do whichever is lesser work and easier to maintain.

2. For the My List items, reduce the font size & left-padding and right-padding by a bit. Something like this (although keep the main text vertically centered).

image


3. Can the weird clipping text of the Kaguya-sama (and similar large name) entries be improved? Maybe if we reduce the clipping character count by a bit?

image


Don't worry about this much though, take your time or fix this in another PR if possible. I just wanted to point these out here.

Otherwise, it all looks pretty good! Should I merge this now or later?

Good day to you ^^

**Comment by baseplate-admin** [comment]
> The scroll now feels much less snappier, like how do I explain it- scrolling amongst the various sections & anime list items feels a bit clunky and broken for some reason. Can this be improved by changing some CSS properties? I [took a look too](https://css-tricks.com/practical-css-scroll-snapping/), and Example 4 is what we're practically aiming for- smooth snapping. I'm not sure if this is possible though, or if it is a problem locked down by the JS. There's also another thing we can do, and that's to remove the scroll snap on all element except for the top carousel. Everything else can just be normal scroll - that way, we needn't worry about the slow snap. You can do whichever is lesser work and easier to maintain.

---

So umm, lets see.

We are using [carousel component from daisy ui](https://daisyui.com/components/carousel/). 

> Can this be improved by changing some CSS properties? I [took a look too](https://css-tricks.com/practical-css-scroll-snapping/),

This is what we are using in mobile version ( can you take a look at that and see if that works for us ? )

> There's also another thing we can do, and that's to remove the scroll snap on all element except for the top carousel. Everything else can just be normal scroll - that way, we needn't worry about the slow snap. You can do whichever is lesser work and easier to maintain.

I dont think this is possible. ( well not entirely impossible but will add churn in our codebase | We can take this route if theres no other option left for us. But lets discuss this further )

So what are we looking for? Example 4 ?

> Can the weird clipping text of the Kaguya-sama (and similar large name) entries be improved? Maybe if we reduce the clipping character count by a bit?


Lemme do the math on this :D 


> Don't worry about this much though, take your time or fix this in another PR if possible. I just wanted to point these out here.

Dont worry. I removed swiper.js because its causing us problems ( like serious problems. Including own DOM controls. Heavy weight dep. Pull to refresh broken. )  Sorry for the troubles though. But i feel like it will help us in the long run. :D 

> Otherwise, it all looks pretty good!

Thaanks :D 

> Should I merge this now or later?

Lets address the problems we have first :D

**Comment by baseplate-admin** [comment]
> Ah it maybe that Firefox renders it much differently than how Chrome & Edge (basically Chromium) does - which may be a reason for this behaviour.

Hmm could be. But does the daisyUi carousel work in chrome?

**Comment by baseplate-admin** [comment]
Hi there. 

The examples work on chrome too. Umm its strange that it doesn't work in your case

Download the video from here please : https://send.vis.ee/download/fb84256e69ec172b/#YL_LQe06YlpNUEb31FgdwQ

**Comment by AKindWorld** [comment]
Huh- that's pretty weird...

What version of Chrome are you on? for me, it's the latest - 104.0.5112.102 Stable.

I'll check on a few other browsers on my device, and get back to you in a few hours.

**Comment by baseplate-admin** [comment]
> What version of Chrome are you on? for me, it's the latest - 104.0.5112.102 Stable.

Latest from https://chrome.google.com

> I'll check on a few other browsers on my device, and get back to you in a few hours.

Take your time. No worries

**Comment by AKindWorld** [comment]
alrighty I checked it a bit- seems like the issue here is the Chromium engine. I'm not sure if it's a bug or not, but it's definitely abnormal. It's present (albeit less) on your video showcase too.

I tested it on Firefox, and it's as smooth as it can get - but on Chrome & Edge (and anything else using the Chromium engine), it's quite janky - atleast it's not as smooth as Firefox.

Here's another example: 

Firefox: https://litter.catbox.moe/zuqczr.mp4

Edge: https://litter.catbox.moe/n0ze41.mp4

(Also, I don't think it's any extensions or add-ons interfering either, since I tested on both browsers with all extensions removed/disabled. The most I can think of is that it's a Chromium bug; or it may be something in the CSS not playing nice for Chromium.)

If you retry it again on Chrome or Edge, notice that the scrolling feels pretty weird compared to Firefox (I can't really describe it - but it's like the animation lags for a bit after you release your mouse wheel).

ah- btw don't worry much about this. Take your time. 

Good day to you ^^

**Comment by baseplate-admin** [comment]
Aha i seee. 

The firefox is performant because of the new [webrender engine ](https://github.com/servo/webrender) that mozilla was working on.

Unfortunately the workaround will break the site on mobile. Its what swiper.js took. Thats why when you scroll you will get a weird pull to refresh thingy. 


Hmmmm not much i can do except file a bug report on google chrome ( will they listen tough ) but i will try working with a new carousel framework to see if we can get some result. 


Ughhhh.. Why cant chrome improve with all the ad revenue that they have :3


----

Thanks again. I will take a look on what i can do

**Comment by baseplate-admin** [comment]
> EDITTTT: Found another problem related to this behavior. On Chromium browsers, varying scroll strength often results in a double slide scroll, while on Firefox - it'll always be 1 slide no matter what. Firefox's behavior is actually what we want, otherwise it's not really snapping.

> Feel free to test it on your device too, if possible. For Chrome/Edge, if you scroll down too hard, it may go down directly to the 3rd slide, while on Firefox it's always the 2nd slide.

Hey @AKindWorld ,

i have applied a patch regarding this. Lemme know if it works :D

**Comment by baseplate-admin** [comment]
> For the My List items, reduce the font size & left-padding and right-padding by a bit. Something like this (although keep the main text vertically centered).


Fixed 


> Can the weird clipping text of the Kaguya-sama (and similar large name) entries be improved? Maybe if we reduce the clipping character count by a bit?

**Comment by baseplate-admin** [comment]
Figure_1

**Comment by baseplate-admin** [comment]
So @AKindWorld 


<details>
<summary>Given this image : </summary>


test


</details>

What background color is the best pick ?


<details>
<summary>Option one : </summary>




index



</details>

<details>
<summary>Option two : </summary>




index




</details>

**Comment by AKindWorld** [comment]
WOOOH is that what I think it is? Image-based color value recognition for the backdrop?

Amazing work so far! I was actually thinking about this the other day xD

I'll also try to implement this in the design to a good extent ^^

About which color is better for that image, would you mind if I let you know in a few more hours? (after I'm back on my PC, I'll test the color values for both)


From first glance though, it seems like - 
a. If going for the _most spread out_ color value, the darker one is better.
b. If going for the _brightest_ value, the lighter one is better (there are other possible values too, depending on how much we can extract and how vivid the artwork's color scheme is).

I'll give you a detailed insight as soon as I can.

Great work so far!! 

^^

**Comment by baseplate-admin** [comment]
> WOOOH is that what I think it is? Image-based color value recognition for the backdrop?

Yep.

> Amazing work so far! I was actually thinking about this the other day xD

Good timing xD

> I'll also try to implement this in the design to a good extent ^^ 

The first one is easy to implement. Because it doesn’t use an artificial intelligence to compute. 

2nd one requires our python backend.

> From first glance though, it seems like -
> a. If going for the most spread out color value, the darker one is better.
> b. If going for the brightest value, the lighter one is better (there are other possible values too, depending on how much we can extract and how vivid the artwork's color scheme is).


I seee...


> EDIT: Is it possible to extract more than 1 color from a particular image? Just curious.

It is Very much possible but at 2x the time. Currently our AI takes a full minute to compute the color values. 

> I'll give you a detailed insight as soon as I can.

I will eaot for it :D

**Comment by baseplate-admin** [comment]
Hi,

@AKindWorld 

can we get some feedback for this :D

**Comment by AKindWorld** [comment]
ahh I'm so sorry for so much delay- I had a lot of work to do suddenly, so I didn't get much time for the past 2 days.

I tested it out a little bit - and it seems like for the backdrop, the first color is the best choice (or maybe I should say the darkest color). 

> It is Very much possible. Look at the graph. We already did take different colors.

If this is possible, then perhaps we can extract a light color for the foreground elements as well. But as for how much good they'd be, I'm not sure.

**1.** 
<details>
<summary>Can you tell me if this is possible? or is it inefficient?</summary>


image
</details>


<details>
<summary>Basically for any image, extract the darkest color for the bg overlay gradient, and the lighest color for the fg elements, which would lead us to this: </summary>


image
</details>

---

 
**2.** 
<details>
<summary>Even if the fg light color extraction is not possible, no worries - our original color choices for the fg elements too are completely usable here, so with that it would look something like this</summary>


image

</details>

-or just about any color from our original color palette.

---

**3.** 
<details>
<summary>If extracting a dark background color seamlessly is not efficient, then we may also go this route.</summary>


image

</details>

This is also much more efficient, and the extracted colors can also be implemented a lot more on the Anime Info page. The best thing is that this method doesn't have the risks of extracting a color that messes with the minimum contrast ratio. What do you think about this?

---

> The first one is easy to implement. Because it doesn’t use an artificial intelligence to compute.
>2nd one requires our python backend.

Yeah, the first one seems pretty good to me, but the outcome will depend independently on the images, so in some cases the first will be better, and in others, the second one.

> Essentially this is a port of my soundcore logics. I wanted to make something like Spotify music player. And thats where most of my code/research comes from

Aha yeah, great work! This is all pretty interesting and cool xD

~~Also, um- sorry for making this comment so much messy.~~ Tried clearing it up a bit.

And, sorry again for the huge delay in replying ;-;

Good day to you ^^

**Comment by baseplate-admin** [comment]
> ahh I'm so sorry for so much delay- I had a lot of work to do suddenly, so I didn't get much time for the past 2 days.

Sorry if i knocked you at a wrong time.

I wanted to get this PR merged. Because this PR contains some QOL fixes. Sorry if i knocked you at a erong time.

Gimme some time to think on this. All of the codes are written in a field i am not familiar with. So i need some time. 

In the meanwhile lets see if we can get some things fixed with our current codebase. But again i am going on a hiatus. With my exams in 3 month i cannot give time to properly code.

**Comment by baseplate-admin** [comment]
Hey @AKindWorld ,

We need to merge this PR to get

`coreproject.vercel.app` working. 

I am transferring your Comment into an issue ;D

**Comment by AKindWorld** [comment]
Hi there!

sorry for being so late in responding back; I was working on some stuff so I'll respond to the new issue in a few more hours (probably).

Btw, don't worry - I don't mind your pings at all. I was actually free that day, so no worries about that xD.

Feel free to merge this PR anytime :) 

Sorry again, and take your time too.

Good day to you ^^

**Comment by baseplate-admin** [comment]
> Feel free to merge this PR anytime :)


I will let you so the honors

**Comment by AKindWorld** [comment]
Merging this! Great work ^^

**Pull request merged**
