### PR TITLE
[ AnimeCore ] Frontend : Add `FROM YOUR LIST`

### PR DESCRIPTION
**Pull request by baseplate-admin**
Hotfixes for #197

### CODE REVIEW

**Comment by baseplate-admin** [comment]
image
image
image

**Comment by baseplate-admin** [comment]
@AKindWorld Take a look at the mobile layout

The one we are targeting :

image


The One we have : 

image

**Comment by baseplate-admin** [comment]
@AKindWorld 
image

**Comment by baseplate-admin** [comment]
@AKindWorld The text should be more than 100 words on desktop?
image

**Comment by AKindWorld** [comment]
@baseplate-admin 

> The text should be more than 100 words on desktop? 

For desktop, you can bump it up to ~500 characters. There will be a lot of blank space anyways. For smaller screens on desktop layout (eg: Tablets/iPads), you can keep it to ~350. 

I'm working on the other stuff (list layouts and error page descriptions) right now; it'll be ready soon ^^

**Comment by baseplate-admin** [comment]
> Edit: Another suggestion; can you increase the bottom padding of the whole text (Title, desc, genres, buttons) a bit? I think this will improve the gradient flow and the scroll below function. Only for desktop. Mobile looks all good!

image

**Comment by AKindWorld** [comment]
**Updates to the `FROM YOUR LIST` section**

Desktop:

image

Mobile: 

image

Mockup: https://www.figma.com/proto/knyOkHUChnJpsAsmuILhOk/Core-Project?page-id=0%3A1&node-id=590%3A9&viewport=241%2C48%2C0.15&scaling=scale-down&starting-point-node-id=590%3A9&show-proto-sidebar=1

image


@baseplate-admin

**Comment by baseplate-admin** [comment]
@AKindWorld this should be everything

**Comment by baseplate-admin** [comment]
#207

**Comment by baseplate-admin** [comment]
@AKindWorld Dont forget to close that too 🗡️

**Comment by baseplate-admin** [comment]
FYI the animation and dropdown items are not yet complete.. I will do it sometime later

**Comment by baseplate-admin** [comment]
@AKindWorld  merge this :D I have almost fixed everything

**Review by AKindWorld — APPROVED** [review]
Good work! Another part done xD

**Pull request merged**
