### PR TITLE
[`Backend`] : move to graphql

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Review by tokitou-san — APPROVED** [review]

**Comment by patrick91** [comment]
why was this reverted? just curious 😊

**Comment by baseplate-admin** [comment]
Hi, Lemme first thank you for maintaining `strawberry-graphql`. It really is an awesome library. I am a huge fan of the library.

Now back to the original question.

First reason : 
The problem i faced at first was that strawberry was fragmented. 
The functionality was spread among :
1. [`strawberry`](https://github.com/strawberry-graphql/strawberry)
2. [`strawberry-django`](https://github.com/strawberry-graphql/strawberry-graphql-django)
3. [`strawberry-django-plus`](https://github.com/blb-ventures/strawberry-django-plus)

Second reason: 
The strawberry docs and the codes are a bit hard to wrap my head around. 
For example [this code](https://github.com/strawberry-graphql/strawberry/blob/5153a6c392859047b206b8a6129f6b50577a4042/strawberry/django/__init__.py#L4) from `strawberry` indirectly imports everything from `strawberry_django` ( which isn't a bad thing, but for some reason vscode's intellisense broke ). 


Third reason : 
Then there's lack of resources ( learning materials ) for strawberry. Strawberry lacks a proper step by step introduction to a small CRUD application that explains how to implement strawberry. Developers are left scrambling the docs ( `strawberry-django`'s docs are pretty good ) to implement basic features. ( some of us can learn faster if there's someone on youtube explaining things ;) ) 


Fourth ( and final ) reason :
I want the strawberry ecosystem to get a bit more mature ( instead of splitting codes among 3 repositories, maybe `strawberry` and `strawberry-django` should be sufficient ) to avoid migrating down the line. I am all in for beta testing ( heck i even wrote this backend in `django-ninja` instead of `djagno-rest-framework` just to try out new things ) but the lack of proper documentation on each module is a bummer for me.

----

But this isn't the end. I am keeping a keen eye on where `strawberry` is headed. Maybe in a few months i would be fully migrating to `strawberry` 


Once again thank you for your interest.

**Comment by patrick91** [comment]
@baseplate-admin feel free to reach out to us on discord! I'll be happy to help 😊

I know @bellini666 wanted to a stream on getting started with strawberry django, so maybe that will help you 😊

**Comment by bellini666** [comment]
> I know @bellini666 wanted to a stream on getting started with strawberry django, so maybe that will help you 😊

Hopefully next week! :)

**Pull request merged**
