### PR TITLE
[ `Frontend` ] : Modify Navbar

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@AKindWorld lets keep the design related discussion in pull requests 🍡

**Comment by AKindWorld** [comment]
Hi there! sorry for the late response; got a bit busy for the past few days.

Huge congrats on deploying it to vercel! Really well done!

> lets keep the design related discussion in pull requests 🍡

yep sure! I'll restart work on the design files from today onwards, so expect a full working prototype soon too ^^

Once again, great work!
Good day to you ahead.

**Comment by baseplate-admin** [comment]
> Hi there! sorry for the late response; got a bit busy for the past few days. 

Same here lol 

> Huge congrats on deploying it to vercel! Really well done!

Thank you. Honestly it was your idea. So thanks for giving me the idea 

> yep sure! I'll restart work on the design files from today onwards, so expect a full working prototype soon too ^^ 

No need to rush. I am going to dial it down a little bit ( have exams and  sorts )

So in the mean time take a look at the navbar design :D

**Comment by baseplate-admin** [comment]
@AKindWorld check this out

**Comment by AKindWorld** [comment]
Yep checked it! Looks extremely good so far; 

also, just a heads up, I'm experimenting with a sidebar navigation UI for desktop (will be auto hidden by default on smaller devices), so you may add that too if you wish to. 

I'll update the `Homepage UI` mockup with it soon. For now, it's in progress in the [`Anime Info Desktop`](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=587%3A1423&node-id=1084%3A1015&viewport=552%2C423%2C0.21&scaling=contain&starting-point-node-id=1084%3A1015) mockup, and I'm working on expanding it.

I think Mantine has a sidebar thingie in the AppShell something something (if we're using it).

About this one, good work!

**Comment by baseplate-admin** [comment]
> Yep checked it! Looks extremely good so far;

Good for merge?

> also, just a heads up, I'm experimenting with a sidebar navigation UI for desktop (will be auto hidden by default on smaller devices), so you may add that too if you wish to.

Hmmm took a look. Will be working on this after some time :D

> I'll update the Homepage UI mockup with it soon. For now, it's in progress in the Anime Info Desktop mockup, and I'm working on expanding it.

Okayy! 

> I think Mantine has a sidebar thingie in the AppShell something something (if we're using it).

We are not using it right now but if you wish we can add it later :D


----

As usual good work :D

**Comment by baseplate-admin** [comment]
But i am doing work in pieces. For example add navbar, add hero slider, add this, add that,.... 

In my limited it helps me focus instead of taking a jab at everything at once and getting almost no visible result

**Comment by baseplate-admin** [comment]
This way you have to click a few more buttons ( i hope you dont mind )

**Comment by baseplate-admin** [comment]
Umm her @AKindWorld  an update on this would be very nice :) As i am a bit stuck without this merging :P 

--- 

I hope i dont bother you much. Thanks :D

**Comment by AKindWorld** [comment]
ahh I'm so sorry! I got a bit busy with something so this went out of my mind.

Yep, this looks all good to me; all ready for merging!
Also, I don't mind it being done in phases. Feel free to take your time!

sorry again! and good job!
Wish you a great day ahead :)

**Review by AKindWorld — APPROVED** [review]

**Comment by baseplate-admin** [comment]
> ahh I'm so sorry! I got a bit busy with something so this went out of my mind.

Opps. I hope i dont disturb you

> Yep, this looks all good to me; all ready for merging!
Also, I don't mind it being done in phases. Feel free to take your time!

Thanks :D

> sorry again! and good job!

Thanks and no worries.

> Wish you a great day ahead :)

same to you

**Pull request merged**
