### PR TITLE
[ `Frontend` ] : Add auth hook

### PR DESCRIPTION
**Pull request by baseplate-admin**
This is technical stuff. 

Essentially we are setting the `HTTP-Only-cookie` from `django` then we are consuming it using react

### CODE REVIEW

**Comment by AKindWorld** [comment]
aha I see. 

_(not that I understand much though)_

Should I merge it now?

**Comment by baseplate-admin** [comment]
> Should I merge it now?

yes

**Comment by baseplate-admin** [comment]
> (not that I understand much though)

Dont worry :P 

Its nothing much

**Review by AKindWorld — APPROVED** [review]
Good work!

can't let Kokoro-chan get hacked >_<

**Comment by baseplate-admin** [comment]
Yaayyyy lets goo

**Pull request merged**
