### PR TITLE
[ `Backend` ] : Improvements

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Continuing #454 ( as i had mistakenly merged it )

**Comment by baseplate-admin** [comment]
@AKindWorld please merge this

Sorry for meging the previous PR. :$

**Comment by AKindWorld** [comment]
Hi hi!

sorry for the delayed response. Should I merge this PR? or are you adding something more to it?

and don't worry about merging the previous PR, I don't mind - I hope accidentally merging it didn't mess up anything on your end.

^^

**Comment by baseplate-admin** [comment]
Hi there.

> and don't worry about merging the previous PR, I don't mind - I hope accidentally merging it didn't mess up anything on your end.

I removed the merge from master. No worries >__< Again sorry. was using the mobile interface.

---

What do you think of this https://github.com/baseplate-admin/CoreProject/pull/454#issuecomment-1208789706

**Comment by baseplate-admin** [comment]
@AKindWorld Please merge this

**Comment by baseplate-admin** [comment]
Lemme add [this](https://www.reddit.com/r/django/comments/r2tti8/comment/hm9ghz5/) to core

**Comment by baseplate-admin** [comment]
Hey @AKindWorld ,

Do you think we need more [endpoints](https://github.com/baseplate-admin/CoreProject/tree/new-backend/backend/apps/api/v1) ?

**Comment by baseplate-admin** [comment]
do we add forum here too ?

**Comment by baseplate-admin** [comment]
Tracker sync is finished :D

**Comment by baseplate-admin** [comment]
Backend reached feature parity with the old one. Good for merging :D

**Comment by baseplate-admin** [comment]
hey @AKindWorld  we are removing swiperjs . Its too much pain to work with

**Comment by AKindWorld** [comment]
Hi hi!

> It messed up a whole lot actually but I removed the merge from master. No worries >__< Again sorry. was using the mobile interface.

oh nothing to apologize for - if anything, it caused more work for you. Take your time - no need to hurry.

> What do you think of this https://github.com/baseplate-admin/CoreProject/pull/454#issuecomment-1208789706 There is something like [this](https://www.reddit.com/r/anime/comments/gqxuy4/i_created_an_aibased_anime_recommendation_site/) but poorly executed

Sounds really amazing to me - it would improve recs seemingly. 

> Also do you think we need a profanity filter for usernames?
Like [this](https://github.com/web-mech/badwords/blob/f4d9dd2f982eb3f5449bdb3fe4af674a6f116f33/lib/lang.json) ?

Not a bad idea - but people may always just find ways to bypass the system. Some may also get irritated by it, so if we do add it, we need to execute it carefully. 

> Do you think we need more [endpoints](https://github.com/baseplate-admin/CoreProject/tree/new-backend/backend/apps/api/v1) ?

Oh I took a look and it seems to be enough for the information we're serving. But what do you think? I'm currently not sure if we need more, since my eyes are skimming over everything. If I do notice something, I'll let you know

> do we add forum here too ?

The code/logic for the forums in the backend? Yup I think. Unless, you wanna add it later or somewhere else - I'm not sure about the underlying technical stuff.

> Tracker sync is finished :D
> Backend reached feature parity with the old one. Good for merging :D

Yay! well done :) 

> we are removing swiperjs . Its too much pain to work with

Alrighty no problem. Also, are we then moving to normal CSS carousels? or should I try to rework the design? if full-screen carousels are an issue, then I can redesign that part (also to be more consistent with the updated design system - I'm dropping gradients and large animated/heavy elements as much as I can - instead I'm working on making it a dynamic layout; see #438 after I update the details there - _not updated yet_)

Good work on everything!

^^

**Comment by baseplate-admin** [comment]
> Alrighty no problem. Also, are we then moving to normal CSS carousels? or should I try to rework the design? if full-screen carousels are an issue, then I can redesign that part (also to be more consistent with the updated design system - I'm dropping gradients and large animated/heavy elements as much as I can - instead I'm working on making it a dynamic layout; see #438 after I update the details there - not updated yet)

Take a look at [this](https://coreproject-q6zdt0vet-baseplate-admin.vercel.app/) deployment. I have removed rootswiper :D

**Comment by baseplate-admin** [comment]
I am tired of working on the backend. @AKindWorld  please merge this while i work on the frontend for a while

**Comment by baseplate-admin** [comment]
Hey @AKindWorld,

We need to merge this to avoid having merge conflicts 

Thanks :D

**Review by AKindWorld — APPROVED** [review]
Well done!  Merging this ^^

**Pull request merged**
