### PR TITLE
[ `Backend` ] : Improve Architecture 

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Hey @AKindWorld,

Can we merge this ?

^_^

**Comment by baseplate-admin** [comment]
image


We have some nice looking output :D

**Comment by baseplate-admin** [comment]
@akindworld what do you think of this?

**Comment by baseplate-admin** [comment]
Hi @AKindWorld, 

We need to merge this :)

Otherwise Dependabot will go haywire :}

**Comment by AKindWorld** [comment]
Hi, sorry for the delay!

Should I merge this right now?

Thanks & great work btw!

**Comment by baseplate-admin** [comment]
@AKindWorld another ping in case you forgot to merge this PR :D 

Our site is broken after : 

* #557

**Comment by baseplate-admin** [comment]
Hey @AKindWorld, 

I have found a way to proxy our media files without exposing the Bucket url...

**Comment by baseplate-admin** [comment]
Hey @AKindWorld, 

I cant seem to get in touch with you. So i am leaving the message in public. 

Merge this Pull Request please. °_° ( most of the work here is stable )  

I am leaving the project for a while :) My exam routine is published and i need some time to focus on my studies. 

But i  have some awesome ideas to make sure our site keeps running in the future. Also i have sent you some discord messages ( if you can please check them out ) 


Thanks :D Have a good vacation :}

**Comment by AKindWorld** [comment]
> I cant seem to get in touch with you. So i am leaving the message in public.

ah I'm really sorry - I had been rather inactive & lazy for the past few days, so it's completely my fault.

> Merge this Pull Request please. °_° ( most of the work here is stable )

Sure! merging this right after this message.
 
> I am leaving the project for a while :) My exam routine is published and i need some time to focus on my studies.

ahh - no worries! Good luck for your exam. We'll resume the work after your exam, and in the meantime, I'll finish up the design as much as I can.

> But i have some awesome ideas to make sure our site keeps running in the future. Also i have sent you some discord messages ( if you can please check them out )

Yup, once again my bad for not yet replying to the Discord messages - huge thanks for all your help in that repo and I'm excited to check out all of the new ideas.

> Thanks :D Have a good vacation :}

Yup! you too, and good luck on your exams! (*oh* - does having exams count as a good vacation though...?)

> Edit 1: If you want to do some works. Please take a look at the color scheme. In my opinion a darker shade will be better :)

Sure, I'll keep that in mind and work on it. I was actually thinking about a themes feature if possible, but thanks for the suggestion :)

Currently I'm working on a fully interactive prototype so look forward to it xD

Wish you a great time ahead ^^

**Review by AKindWorld — APPROVED** [review]
Great work! Merging this :)

**Comment by baseplate-admin** [comment]
Hi there,

---

> ah I'm really sorry - I had been rather inactive & lazy for the past few days, so it's completely my fault.

No worries... Sorry if i pinged you too much... 

> ahh - no worries! Good luck for your exam. We'll resume the work after your exam, and in the meantime, I'll finish up the design as much as I can.

I will work at full force ( hopefully. I am also looking to get a part time job as a programmer at a local startup. Hopefully our site will finally be live ) hopefully a new vomouter too ( wanna play genshin together? ) 

> Yup! you too, and good luck on your exams! (oh - does having exams count as a good vacation though...?)

Vacation for you, hell for me :')


> Yup, once again my bad for not yet replying to the Discord messages 

No worries... :D 

> huge thanks for all your help in that repo and I'm excited to check out all of the new ideas.

Lemme know if you guys need any help.

> Sure, I'll keep that in mind and work on it. I was actually thinking about a themes feature if possible, but thanks for the suggestion :)

By that.. Do you mean a toggle ( like discord? DaisyUI is perfect for this ) 


> Currently I'm working on a fully interactive prototype so look forward to it xD

I am doing a prototype proxy ( which can serve media files without ever exposing the request url | if this is successful, we might never need a VPN and we will be DMCA proof ) 


----

Takw care till i return ( i can still answer questions here tho 👀)

**Pull request merged**
