### PR TITLE
[ `Frontend` ] : Next slide

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by AKindWorld** [comment]
Hi there! sorry for the delay in responding

Benchmarked it with web.dev again, here are the results - [Link](https://web.dev/measure/?url=https%3A%2F%2Fcoreproject-mktk4di7c-baseplate-admin.vercel.app%2F)

image

Quite a lot of performance improvement so far. Good job! Also, on that note, I have compressed the original images by quite a lot (~50%); I'll send them to you in a bit.

Also, any updates on your PC?


Wish you a good day ahead :)

**Comment by baseplate-admin** [comment]
> Hi there! sorry for the delay in responding

I am quite busy myself. Because of Eid and all the stuff.

> Quite a lot of performance improvement so far. Good job! Also, on that note, I have compressed the original images by quite a lot (~50%); I'll send them to you in a bit.

Used AVIF. :D. Waiting for new your new images :D 

----

> Also, any updates on your PC?

https://github.com/baseplate-admin/CoreProject/issues/404#issuecomment-1178914791
The fault is mine on this. I tried to reseat the processor and i accidentally bent it.
Sadly i can develop but at a 20× lower rate. ( i stole my mothers laptop :D )

**Comment by baseplate-admin** [comment]
This site has no mobile version. Right?

**Comment by baseplate-admin** [comment]
@AKindWorld  @tanimsk [looks like my commit has reached twitter](https://twitter.com/sassy_commits/status/1417191070438469644)

**Comment by baseplate-admin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1683250

https://stackoverflow.com/questions/71589733/swiper-js-is-laggy-on-android-with-free-mode-loop-and-auto-play

https://stackoverflow.com/questions/60438838/swiperjs-custom-speed-delay-for-each-slide

---


All of these points the obvious :| 


How to make swiper faster?

**Comment by baseplate-admin** [comment]
hey @akindworld, I have identified the problem with slow page load :D Please check the latest deployment to see if you can figure it out 😉

**Comment by baseplate-admin** [comment]
https://github.com/nolimits4web/swiper/issues/5871 Unless this gets fixed. The slider progress will always be hacky. I can make the slider work at the cost of performance. ( but is it worth it ? )

**Comment by baseplate-admin** [comment]
after near about 2 hours of fiddling i can say for sure the UX is 90% better

**Comment by baseplate-admin** [comment]
But i am not satisfied with performance... 90% of the blame goes to the stack we chose

**Comment by AKindWorld** [comment]
Hi there!

Here are the images (compressed by ~70% from the total): https://catbox.moe/c/2nhavs

hopefully this improves the network load by a bit (it can be reduced even further but we'll see about that later on)

> I have identified the problem with slow page load :D Please check the latest deployment to see if you can figure it out

I think it's the progress bar? It's no longer time-based, right? No worries though, I think it's all cool as it is if it improves performance. Actually, if it improves performance, feel free to leave out the progress bar completely. Just the dots & the next/previous buttons are pretty good by themselves.

>  This slide has no mobile version. Right?

Hmm, so for the app layout, the search bar is embedded on the top/header. So, if we're going that route, feel free to leave out this part for the mobile website. If however, making a search header is not possible, then just include the search bar for the mobile website in this part.

image

---

So, all in all, yup - the desktop version looks pretty nice and works good. There are small stuff that can be improved here & there (I'll point those out later on) but overall it's pretty good. Good job!

also congrats on getting mentioned on Twitter xD
and hope you get a new PC soon! take your time in developing.

Good day to you \\^o^/

^^

**Comment by baseplate-admin** [comment]
Adding in the changes. 🗡️ 

---

What about performance.  I have changed internal architecture quite a bit. Would you mind benchmarking it? :D thanks :D

**Comment by baseplate-admin** [comment]
> I think it's the progress bar? It's no longer time-based, right? No worries though, I think it's all cool as it is if it improves performance. Actually, if it improves performance, feel free to leave out the progress bar completely. Just the dots & the next/previous buttons are pretty good by themselves.

For now lets leave it out. If https://github.com/nolimits4web/swiper/issues/5871 gets addressed we will re add the progress bar :D 

> Hmm, so for the app layout, the search bar is embedded on the top/header. So, if we're going that route, feel free to leave out this part for the mobile website. If however, making a search header is not possible, then just include the search bar for the mobile website in this part.

This is a good approach for what i was looking for. Lemme add it in

**Comment by baseplate-admin** [comment]
@AKindWorld  i also have another request. The white text on white background images look very white ( wow inlish ).

image

**Comment by baseplate-admin** [comment]
This should be everything :D

**Comment by baseplate-admin** [comment]
https://github.com/albert-gonzalez/easytimer-react-hook

**Comment by baseplate-admin** [comment]
Hey i am readding the slider. I have found a performant way to handle updates

**Comment by baseplate-admin** [comment]
Fixed Timer

**Comment by baseplate-admin** [comment]
@AKindWorld give it a final review and merge this

--


Thanks :D

**Comment by AKindWorld** [comment]
Hi there!

Great work on making the time progress bar work; it looks great!

I think this PR is pretty much done; just a few small suggestions:

- Can you make the increase the margin-top for these elements (for bigger screens):

image

- And increase the left for the search icon (to 5px) & padding-left for the input text (from 60px to 70px):

image

- Another issue I noticed is that for the mobile layout, the search bar text gets reset during the carousel auto-switch.

That's pretty much it! I assume that you'll be working on the search bar & dropdowns later on? The search won't work now anyway, so it's all good.

> I will start working on the next slide. Please send the images

Yup alrighty. For now, you can use the anime posters as placeholders (set as fill). If they look good, we'll keep it at that. If they don't, I'll check up some mid-res posters & official art & send it. 
Under the Continue Watching section, you can use the images we used in the carousel (for Shield Hero & Kaguya-sama).

I'll try to add in some info for the elements in the main Figma file (below the current ones).

> i also have another request. The white text on white background images look very white ( wow inlish ).

Ah yeah true. I looked into it a bit, and there are a couple of fixes we can apply - but I'll check around a bit more. Looks like an unnoticed contrast issue - I didn't predict that happening for smaller screen sizes, so it's my fault. Also lol xD

Also, about performance, I benchmarked several preview releases & the production release... and it's going haywire - desktop values ranging from 65-85 and mobile values 45-65 on average. I'll probably send you a detailed report on the next PR.

---

sorry for the delay in replying

Amazing work! Good day to you :)

^^

**Comment by baseplate-admin** [comment]
> Can you make the increase the margin-top for these elements (for bigger screens):

Sure.. Gimme 1 hour

> And increase the left for the search icon (to 5px) & padding-left for the input text (from 60px to 70px):

Oh wait. This is set by `mantine` ( that means i would rather not touch these ). Is it absolutely necessary? 

> Another issue I noticed is that for the mobile layout, the search bar text gets reset during the carousel auto-switch.

This is not suppossed to happen. Lemme diagnose it a bit

> Ah yeah true. I looked into it a bit, and there are a couple of fixes we can apply - but I'll check around a bit more. Looks like an unnoticed contrast issue - I didn't predict that happening for smaller screen sizes, so it's my fault. Also lol xD

Ah no worries.. Adding a font border would be enough dont you think 👀

> Also, about performance, I benchmarked several preview releases & the production release... and it's going haywire - desktop values ranging from 65-85 and mobile values 45-65 on average. I'll probably send you a detailed report on the next PR.

The reason is probably caching.  So we can expect 85 in most cases. But developing on a slower laptop made me realize what was going wrong. Lol xD

> Yup alrighty. For now, you can use the anime posters as placeholders (set as fill). If they look good, we'll keep it at that. If they don't, I'll check up some mid-res posters & official art & send it.
> Under the Continue Watching section, you can use the images we used in the carousel (for Shield Hero & Kaguya-sama).

Got it


---

Did you notice? I fixed the tags? 👀

**Comment by baseplate-admin** [comment]
Anyways lets merge this Pull Request.  I will address more issues in the next one.

Thanks :D. Wishing you a good fay

**Comment by baseplate-admin** [comment]
I did more benchmarks and you know what happened? 

The `ScrollArea` widget is causing 99% of the problems

**Comment by AKindWorld** [comment]
Hi there!

> Oh wait. This is set by mantine ( i would rather not touch these ). Is it absolutely necessary? Besides i plan to rework on this input thing. ( mobile search bar already can show dropdown )

Oh I see. No worries then; also yup, I'll design a search bar layout too later on, although I'm not sure if it's possible to customize.

> Oh wait this is a design decision. The whole slide is refreshed. There is no way to preserve state. You can also see the progress bar disappearing.

I see. Hmmm... is it possible to pause the AutoSlide on the search bar focus? (kinda like what we have for the description box in desktop)

> Ah no worries.. Adding a font border would be enough dont you think

Yup, pretty much. There are also some other ways I was looking into, but this seems to be an universal solution.

> Did you notice? I fixed the tags? 

yup yup! and they look amazing!

> The BackgroundImage widget is causing 99% of the problems. Would you mind sending lower res pictures ? Somewhere in between 512kb

yup, here you go! - https://catbox.moe/c/2nhavs
All images are under 0.5 MB, and the total filesize is ~ 3.5 MB.

> Anyways lets merge this Pull Request. I will address more issues in the next one.

Yup, alrighty then! I'll just wait for you to update the images, and then merge it. Great work so far though :)

Good day to you!

^^

**Comment by baseplate-admin** [comment]
Fixed everything ;D

**Comment by baseplate-admin** [comment]
Umm hey @AKindWorld,  do you mind if we rewrote this whole thing in `svelte` + `smui`? 

React is can't just one page, can you imagine how much slower it will become if we start adding more components?

**Comment by AKindWorld** [comment]
> Umm hey @AKindWorld, do you mind if we rewrote this whole thing in `svelte` + `smui`?
> 
> React can't handle just one page, can you imagine how much slower it will become if we start adding more components?

No, I don't mind at all either way, but with what I saw for SMUI, would it be possible to customize it to this extent? Also, can we use this many versatile elements? In my personal opinion, SMUI is very very basic by itself (which is both a good thing & a bad thing).

If however, we can customize it & make it similar to this one, then feel free to take your time and rewrite it. Tbh, you're right about this stack being slow - I tested it with my chromebook yesterday & it couldn't handle a single tab - while for other anime sites, it can handle ~20-30 tabs at a time. I just don't feel the difference on my PC, but yeah, it's pretty laggy on lower-end devices, and might become even more so.

EDITTTTTT: noticed your edit just before clicking :P 
what're some other libraries besides SMUI that we can use? 

^^

**Comment by baseplate-admin** [comment]
> EDITTTTTT: noticed your edit just before clicking :P
what're some other libraries besides SMUI that we can use?

Svelte is not mature. We can make something with TailwindCSS + DaisyUI. If we go that route i believe we can clone what we made so far


---

One more selfish request.  Can you please test the svelte v3 site?

**Comment by baseplate-admin** [comment]
>  I tested it with my chromebook yesterday & it couldn't handle a single tab - while for other anime sites, it can handle ~20-30 tabs at a time.

Initial component hydration is very slow on react. Why does people use react to this extent i wonder.

**Comment by baseplate-admin** [comment]
Just to fix a timer i had to rewrite this whole app 5 times. And even then the timer is not correctly working. I mean VUE did everything. It has more functionality and its faster than react. Facebook UI is another Shit. God i hate react

**Comment by baseplate-admin** [comment]
Sorry for all the rant. I am frustrated with react. I feel like i am burning out. 


I will take a break and rewrite everything. Thanks for your help here. I wish you a good day.

**Comment by AKindWorld** [comment]
> Svelte is not mature. We can make something with TailwindCSS + DaisyUI. If we go that route i believe we can clone what we made so far

I see. Daisy UI looks amazing to me, so we can use that (even with zero customization, it would look cool).
 
> One more selfish request. Can you please test the svelte v3 site?

Yup, sure! do you have a deploy link for it? 

^^

**Comment by baseplate-admin** [comment]
So the libraries we can use for svelte are CSS only libraries

Like : 

1. Bulma
2. Tailwind
3. Bootstrap

Good component libraries for svelte are : 

1. SMUI

Rest from this list : https://madewithsvelte.com/ui-library


But in my opinion lets go CSS only. Makes porting components that much easy.


----

> do you have a deploy link for it?

I am afraid not. You would have to build it somehow. For now lemme take a look into vercel :) lets see if i can monkey patch some stuff

**Comment by baseplate-admin** [comment]
But @AKindWorld for now lets merge this :) i will open a new issue with the new framework :) 

Thanks ^___^

**Comment by AKindWorld** [comment]
Alrighty! merging this then :)

^^

**Review by AKindWorld — APPROVED** [review]

**Pull request merged**
