### PR TITLE
[ `Architecture` ] : Add Caddy, made FromYourList better.

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
https://github.com/abiosoft/caddy-exec

**Comment by baseplate-admin** [comment]
Finally fixed eslint

**Comment by baseplate-admin** [comment]
pre-commit.ci run

**Comment by baseplate-admin** [comment]
needs full rewrite

**Comment by baseplate-admin** [comment]
https://www.npmjs.com/package/express-subdomain

**Comment by baseplate-admin** [comment]
We again reverted to micro frontends 😑

**Comment by baseplate-admin** [comment]
Hey i am doing a little bit of hack to get everything working

`https://coreproject.moe/animecore/`    ➜      `AnimeCore ( Static Files )`
`https://coreproject.moe/soundcore/`    ➜      `SoundCore ( Static Files )`
`https://coreproject.moe/api`                   ➜       `API ( Django )`
`https://coreproject.moe/admin`              ➜        `Admin ( Django )` 
`https://coreproject.moe/faq`                  ➜        `FAQ ( Django | Flatpages )` 

While they can be mapped to subdomain 

`https://coreproject.moe/animecore/`    ➜      `AnimeCore ( Node.js / Python http.server )`        ➜        `https://animecore.coreproject.moe/`
`https://coreproject.moe/soundcore/`    ➜      `SoundCore ( Node.js / Python http.server )`        ➜        `https://soundcore.coreproject.moe/`
`https://coreproject.moe/api`                   ➜      `API ( Django )`                                                                      ➜        `https://api.coreproject.moe/`
`https://coreproject.moe/admin`               ➜      `Admin ( Django )`                                                                 ➜        `https://admin.coreproject.moe/`
`https://coreproject.moe/faq`                   ➜       `FAQ ( Django | Flatpages )`                                           ➜       `https://faq.coreproject.moe/`

Caddy doesn't support mapping `file serving` to `sub-domains`. The main problem is if we use subdomain we need multiple `node.js` apps to do `SSG`.

So we have 2 choices.

1.  Ditch Caddy and roll with NGINX ( with certbot ) ( **BEST CHOICE** ) ( But will take some time since i never used **NGINX** )
2. Open an issue in https://github.com/caddyserver/caddy or https://caddy.community/ ( Seems the most logical thing to do )

**Comment by baseplate-admin** [comment]
https://www.npmjs.com/package/pm2

We need this

**Comment by baseplate-admin** [comment]
https://github.com/flekschas/svelte-simple-modal

**Comment by baseplate-admin** [comment]
image


@AKindWorld Review please

**Comment by baseplate-admin** [comment]
@AKindWorld  Your design is not copied 1:1 ( for bulma )

can you please change your design based on this ?

**Comment by AKindWorld** [comment]
> can you please change your design based on this ?

Sure! Well done on the work :)

**Comment by baseplate-admin** [comment]
https://svelte.dev/repl/5f57abd90c4d4c8b89dd3d632e27dc3b?version=3.38.2

**Comment by baseplate-admin** [comment]
https://amalshaji.com/blog/sveltekit-nprogress

**Comment by baseplate-admin** [comment]
@AKindWorld merge this.. We can always make new PR to reflect changes..

**Comment by baseplate-admin** [comment]
pre-commit autoupdate

**Comment by baseplate-admin** [comment]
pre-commit.ci autoupdate

**Comment by baseplate-admin** [comment]
pre-commit.ci autofix

**Pull request merged**
