### PR TITLE
[`Backend`] : Improvements

### PR DESCRIPTION
**Pull request by baseplate-admin**
Breif summary of what i have done

1. I have decoupled django. Which lets us make an microservice type application. 
2. I have implemented a proxy server ( which is a glorified VPN what routes media files through our server | DMCA prevention ) 
3. I have implemented `AioHttp` which lets us use discord.py.
4. I Have charted discord bot functionality. ( more on this on https://github.com/baseplate-admin/CoreProject/issues/305#issuecomment-1256936679 ) 
5. I have implemented full text search functionality. ( basically how google filters search.  We take an input and search it in our database and rank it using GIN algorithm ) 

----

What i need now is a landing page for our aiohttp app. Which should include :
1. Tech stack
2. Some fancy logo? ( i have all the logos ) 
3. An old bartender type thingy? ( something to match barista but has to be anime type? And should be 4k/SVG | I will look for this. But if something catches @akindworld 's eye lemme know ) 

----

Also i have started to name our services. ( since we are doing a microservice architecture) 
1. `AioHttp` -> Barista ( since it serves same purpose as a bartender | Serve Files )

---

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Oofff thats a lot of work i had to do to get this Pull Request up-to-date

**Comment by baseplate-admin** [comment]
@AKindWorld lets merge this :D

**Review by AKindWorld — APPROVED** [review]
Great work! 

^^

**Comment by baseplate-admin** [comment]
@AKindWorld take a look here 

https://litter.catbox.moe/ujlnl9.jpg


** delete this message afterwards **

**Pull request merged**
