### PR TITLE
[`Backend`] : Expose `created_at` and `updated_at` fields

### PR DESCRIPTION
**Pull request by baseplate-admin**
@AKindWorld & @sssuneeth  this is my initial attempt to get the `created_at` and `updated_at` functionality (which is required for the graph feature).

Graph Feature : https://anilist.co/site-stats

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@sssuneeth I would like your review on this

**Comment by sssuneeth** [comment]
>  this is my initial attempt to get the created_at and updated_at

You mean that DateTimeField?

**Comment by baseplate-admin** [comment]
> You mean that DateTimeField?

Correct

**Comment by sssuneeth** [comment]
Yea, We need that fields, I used to think you already implemented.
But the problem is its 5.5 hours before my timezone

**Comment by baseplate-admin** [comment]
> But the problem is its 5.5 hours before my timezone

Lol yes. The times are utc

**Pull request merged**
