### PR TITLE
[ `Architecture` ] : New frontend

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Hey @AKindWorld 

Would you mind giving me the values for color in here : https://daisyui.com/theme-generator/

**Comment by baseplate-admin** [comment]
```
file:///C:/Users/Asus/Desktop/CoreProject/frontend/AnimeCore/node_modules/swiper/solid/loop.js:2
import { effect as _$effect } from "solid-js/web";
         ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (C:\Users\Asus\Desktop\CoreProject\frontend\AnimeCore\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50381:21)
    at async eval (/src/routes/index.tsx:12:31)
    at async instantiateModule (C:\Users\Asus\Desktop\CoreProject\frontend\AnimeCore\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:9)
    
```

**Comment by AKindWorld** [comment]
Hi there!

> Would you mind giving me the values for color in here 

here you go! 

```
"primary": "#7569E1",        
"secondary": "#E3BD49",
"accent": "#FFF7F8",
"neutral": "#1E2036",
"base-100": "#070519",
"info": "#DCD9F7",
"success": "#6FCF97",
"warning": "#EDD68D",
"error": "#EB5757"
```

image

some of the values may change a bit later on, but mostly, it should be good.

good luck & let me know whenever you need anything else!

^^

**Comment by baseplate-admin** [comment]
My man i am blown away by our current stack. I am feeling confident with this :)

**Comment by baseplate-admin** [comment]
Hey @AKindWorld ,

We need rework on badges :) 

Take a look at current deployment 

---

Thanks :D

**Comment by baseplate-admin** [comment]
70% of the ui is complete 


@AKindWorld  please review 

---

^_^ thanks

**Comment by baseplate-admin** [comment]
@AKindWorld  i can apply optimization from react. But for svelte we have a higher margin before we need to optimize things. So the question is should i apply the optimization?

App with optimization : https://coreproject-gp2kak9lw-baseplate-admin.vercel.app/

App without optimization : https://coreproject-35dutnftr-baseplate-admin.vercel.app/

**Comment by AKindWorld** [comment]
Hello!

So currently it looks like this on my monitor:
image

Some suggestions:
1. ~~For the description texts, the scroll doesn't work by default (probably due to the underlying carousel scroll).~~ EDIT: now works.  Also, it would be best if we can use a custom scrollbar or hide the scrollbar (kinda like Mantine does it).
2. Arrow & Indicators for the carousels - I'm sure that you're probably working on those/will work on it later.
3. The buttons & badges can be a bit more rounded, but no need to worry about it right now - I'll go over it later on.
4. Alignment & indentation stuff here & there for the most part.


Performance is... great job! well done :)
image


Great work so far!

^^

**Comment by AKindWorld** [comment]
> i can apply optimization from react. But for svelte we have a higher margin before we need to optimize things. So the question is should i apply the optimization?

Tbh I don't notice any visual changes at all between the two. As for the underlying performance & stuff, they look pretty much the same to me as well. 

So, I'd suggest you to do whichever way you feel is best. I'm not too much knowledgeable about these stuff either, so I might not be able to make a good choice here.

^^

**Comment by baseplate-admin** [comment]
So heres how it looks on Firefox

image


( lets poison chrome users with large scrollbars ☠️ )

JK looking into it

**Comment by baseplate-admin** [comment]
> ~For the description texts, the scroll doesn't work by default (probably due to the underlying carousel scroll).~ EDIT: now works. Also, it would be best if we can use a custom scrollbar or hide the scrollbar (kinda like Mantine does it).

Added

**Comment by baseplate-admin** [comment]
> Alignment & indentation stuff here & there for the most part.

I actually copied the original slide's position. Everything fits perfectly with the original implementation ( AFAIK ) but dont worry. Just lemme know if you need something changed

**Comment by baseplate-admin** [comment]
> Performance is... great job! well done :)

This is why you should offload Layout to the C++ stack. ( but Rich did a good job in creating Svelte. Its just the right amount of magic and performance )

By the way since we are using a CSS only stack we can switch framework at any point in time without no rework :) 

---

Thanks :D

**Comment by baseplate-admin** [comment]
> Tbh I don't notice any visual changes at all between the two. As for the underlying performance & stuff, they look pretty much the same to me as well.

I have applied 1 layer of optimization. :) If we need in future we can apply more :)

**Comment by AKindWorld** [comment]
> I actually copied the original slide's position. Everything fits perfectly with the original implementation ( AFAIK ) but dont worry. Just lemme know if you need something changed

Aha I see. I think we may need to adjust stuff just a lil bit here & there. Can I take a look at the latest version?

> Also to be honest i am glad we made the call. Compared to react this is 200x faster. In future it might have been necessary to switch stack. That time we would have faced a greater issue :)

Yup indeed.

^^

**Comment by baseplate-admin** [comment]
> Aha I see. I think we may need to adjust stuff just a lil bit here & there. Can I take a look at the latest version?

 Sure. Everything except pagination works, Π

**Comment by baseplate-admin** [comment]
Umm wait. we have a problem

**Comment by baseplate-admin** [comment]
Yep, Now  everything should work fine. Sorry i thought it was a problem with your browser :) 

Enjoy the site 

^_^

**Comment by AKindWorld** [comment]
Hi there!

Thanks; well done on the fixes!

Just a few stuff here & there - here's a small comparison

**Previous version:** 
image

**Current Version:** 
image

Some stuff that would be great if you can fix them are - 

1. The background gradient portion - currently it's a shade of #070519 all over; if possible, it would be best if there's the app backdrop gradient. 

2. For bigger screens, it seems like the text & entries are a bit too much centered. Probably not a problem for smaller screens tho.

3. Adding to the above text, it would be great if the max width of the description text is a bit larger for bigger screens.

4. Would it be possible to use a custom scrollbar thumb & bar for the description text part. It kinda looks like this now, it looks a bit off on chrome (& possibly some other browsers). The one Mantine used looked pretty good - transparent background & rounded bar.
image

5. Adding to the above point, it seems that for some reason there's a scrollbar on the Heading/Title (maybe a line height problem?)
image

6. Can you make these fully Uppercase? I think it would look better that way.
image

---

This is pretty much all the visual issues I've encountered so far. Feel free to take your time in fixing them if possible.

Thanks a lot for your work! Lemme know if there's anything you need.

Wish you a well day ahead!

^^

**Comment by baseplate-admin** [comment]
> The background gradient portion - currently it's a shade of #070519 all over; if possible, it would be best if there's the app backdrop gradient.

So umm do we want the previous Version? ( its actually very easy to import that style )

**Comment by baseplate-admin** [comment]
> For bigger screens, it seems like the text & entries are a bit too much centered. Probably not a problem for smaller screens tho.

Umm lemme take a look. Currently the whole thing is a grid. I should use flexbox before the grid. Thanks for pointing this :D

**Comment by baseplate-admin** [comment]
> Adding to the above point, it seems that for some reason there's a scrollbar on the Heading/Title (maybe a line height problem?)

Umm no. Its a design decision. The mantine version also contained this :).  Lemme fix it so that it doesnt show unless overflowed

**Comment by baseplate-admin** [comment]
The scrollbar headache can be solved Tomorrow :) For now i will address the other problems

**Comment by baseplate-admin** [comment]
@AKindWorld I have fixed the scrollbar :) Take a look

**Comment by baseplate-admin** [comment]
@AKindWorld 

Which of these shadow looks good :

1. https://coreproject-ansjpra50-baseplate-admin.vercel.app/
2. https://coreproject-49sbgnmwh-baseplate-admin.vercel.app/

---

Personally i like the 1st shadow. If you can manage to fix the contrast on that I think it will be better

**Comment by AKindWorld** [comment]
Hi there! sorry for the delay

> I have fixed the scrollbar :) Take a look

Yup, well done on fixing the scrollbar. Looks great now!

> Which of these shadow looks good :

I agree on the 1st one too. Looks much better; about the contrast issue, I think, as you suggested, a text border would be the best choice. Is it possible thru just CSS properties? 
If it's not possible/hard to do, then a second choice would be too add a tint overlay on the background and a third option would be to make the description background darker on hover.

Ah also another thing - the text entries are now too much low on my screen. Here's a screenshot:
image
However, this isn't completely an issue. Just a bit higher + the pagination would probably make it look great. 

And another question - is it possible to remove this veryyy small outline thingie on the badges/tags? 
image
Also, can you make it use Kokoro Bold on the badge text? No worries if it can't be done though. Well done on making it Uppercase btw!


Thanks a lot for your work!

^^

**Comment by baseplate-admin** [comment]
Hey i think the latest layout fixes everything :) 

Lets roll with it. :D

**Comment by baseplate-admin** [comment]
Hey we have a problem.

This explains why react is acting the way it was. We need to rethink our approach. 

ref = https://medium.com/airbnb-engineering/css-box-shadow-can-slow-down-scrolling-d8ea47ec6867


We cant use the first method in https://github.com/baseplate-admin/CoreProject/pull/420#issuecomment-1188941082 :)

---

After rewriting this whole thing i am feeling like a loser . F**k I should have guessed where the problem was

**Comment by baseplate-admin** [comment]
say do you want to return to our old stack?

**Comment by AKindWorld** [comment]
> ref = https://medium.com/airbnb-engineering/css-box-shadow-can-slow-down-scrolling-d8ea47ec6867
> We cant use the first method in https://github.com/baseplate-admin/CoreProject/pull/420#issuecomment-1188941082 :)

Ah I see - hmmm that indeed seems to be an issue then; without box shadows, our carousel & anime info pages' main attraction is lessened by a significant lot. Without shadows, it would look very plain, while with a tint (like the one we currently have), it looks a bit dull. Also, this would affect almost all images in the site since I chose gradients as design system value. Hmmm... hard choice to make here.

I took a look too, and it seems that specifying the image-width might work as a solution [here](https://stackoverflow.com/questions/8993541/extremely-slow-css3-box-shadows-in-chrome).
Although in our use case, that is still not possible.

There are 3 things we can now do - 
1. Roll out the existing website with the method 2 (fixed tint). The drawback is that it won't look that good now since one of our main design strongpoints is gone. Also, I'll need to redesign some elements this way since not everything would work with a Tint.
2. Redesign all the layouts completely without using box-shadows. The drawback is that it's time-taking & a lot of the work you did will have to be redone once more.
3. Kinda a hacky way, but we can use our images with a pre-placed box shadow itself. This requires zero effort on the frontend & design, but will require work during the database entries thingie. Not too much though, but just a bit of manual effort, although I should be able to do it by myself. Also since we're using custom images anyway, I feel like this is a pretty good solution by itself. 

As for our stack, I have no problems with either, so feel free to choose whichever you feel is best & you're comfortable working with :)

---

Don't worry though, it's not your fault at all. Bug & issues like this should be widely documented so that developers don't run into the same, but well... ¯\\_(ツ)_/¯

Good day to you!

^^

**Comment by baseplate-admin** [comment]
> Roll out the existing website with the method 2 (fixed tint). The drawback is that it won't look that good now since one of our main design strongpoints is gone. Also, I'll need to redesign some elements this way since not everything would work with a Tint.

This would be the way we should go ( i feel like ) 

> Redesign all the layouts completely without using box-shadows. The drawback is that it's time-taking & a lot of the work you did will have to be redone once more.

Umm if you can do it i can rewrite everything.  But the work on your part will be harder ( and i really liked your current design ) 

> Kinda a hacky way, but we can use our images with a pre-placed box shadow itself. This requires zero effort on the frontend & design, but will require work during the database entries thingie. Not too much though, but just a bit of manual effort, although I should be able to do it by myself. Also since we're using custom images anyway, I feel like this is a pretty good solution by itself.

We have 128,000 images in our database. Rewriting the project will take less time than doing the programming to automate the image process

----


> Don't worry though, it's not your fault at all. Bug & issues like this should be widely documented so that developers don't run into the same, but well... ¯\(ツ)/¯

Welcome to the world of frontend programming 

---


All in all i feel very stupid. And i am burning out. Sorry i will take another break.

**Comment by baseplate-admin** [comment]
hey @AKindWorld  i have fixed the issue. take a look at the latest deployment :D Thanks :)

**Comment by AKindWorld** [comment]
> i have fixed the issue ( more like monkey patched it) . take a look at the latest deployment :D Thanks :)

Whoa amazing! It looks really great, and performance is still intact (score at 99-100)! Really well done; now the design is saved.

With this, I think this part is pretty much done, except for some small things here & there. If you'd like to, I'll point those out, and after that, we can move on to the next part [search & preferences].

Once again, well done! It looks & works great \\^o^/

^^

**Comment by baseplate-admin** [comment]
Hey @AKindWorld 

Do you have any idea on how to fix the contrast issue? Any article or something ?

**Comment by baseplate-admin** [comment]
https://github.com/sveltejs/rfcs/pull/22

:) Why cant there be nice things ?

**Comment by baseplate-admin** [comment]
i have added a class `[text-shadow:-1px_-1px_0_#000000,1px_-1px_0_#000000,-1px_1px_0_#000000,1px_1px_0_#000000]`

Which translates to 

```css
    .text-shadow {
                 text-shadow:-1px -1px 0 #000,
                           1px -1px 0 #000,
                          -1px 1px 0 #000,
                           1px 1px 0 #000;
      }
```

**Comment by baseplate-admin** [comment]
> As you said, font-borders would work great & most importantly, universally. I tested it on the Inspector & it looks pretty good on the Titles but looks a bit cluttered on the description text. But with some tinkering, it can be fixed. The CSS text-shadow property works good for this one. Unfortunately, looks like you'll need to add it using custom CSS or so.

I just added it XD

**Comment by baseplate-admin** [comment]
> A second thing I was thinking of is using a hover effect on the text description area to make it work. I tried to recreate it in the Inspector; it would look something like this:

This looks good :D 

Do you have the file ? Or are you willing to tell me the color values ?

**Comment by baseplate-admin** [comment]
Check now ;) 

The color changes are live

**Comment by baseplate-admin** [comment]
@AKindWorld  we are getting traffic from reddit.

image

**Comment by AKindWorld** [comment]
> Do you have the file ? Or are you willing to tell me the color values ?

Ah I can give you the color values -

for the background, make it #070519 at about 40-50% opacity. Just so it doesn't look out of place, you can change the border raidus of the div to about 12px, if possible. If not, it's still okay :)

For the text color, make it #FFFFFF at 100% opacity.

You can create a custom class for this one, since we may need to reuse it later too.

Well done on implementing the text-shadows btw.

^^

**Comment by baseplate-admin** [comment]
Umm do we still need the background ? 

Or is it fine as it is?

**Comment by baseplate-admin** [comment]
Hey @AKindWorld  the mobile site is ready :) Please do the final review and merge this PR

**Comment by baseplate-admin** [comment]
Fixed :)

**Comment by baseplate-admin** [comment]
Anything more ?

**Comment by AKindWorld** [comment]
> Anything else i missed ?

Just checked, and it looks all great! All good for merging xD

oh just- the text description for Hyouka seems to have a repeated sentence in the beginning; I know the entries are just a placeholder, but if possible, you can fix it in the next part. 

Should I merge this right now?

^^

**Comment by baseplate-admin** [comment]
> oh just- the text description for Hyouka seems to have a repeated sentence in the beginning; I know the entries are just a placeholder, but if possible, you can fix it in the next part.

Umm i cant seem to find it. Would you please send an SS ?

**Comment by baseplate-admin** [comment]
The changes are live :D

**Comment by baseplate-admin** [comment]
Hey @AKindWorld,

I have modified the CSS engine.

Please take a look if you notice something unusual. Thanks :D

**Comment by baseplate-admin** [comment]
Hey @AKindWorld  i have finished the next slide :) 

It is a bit different from the old one. please take a look :D

**Comment by baseplate-admin** [comment]
@AKindWorld  this implementation has reached feature parity with master


( Next.JS + React + Mantine ) => https://coreproject-ansjpra50-baseplate-admin.vercel.app/
( SvelteKit + Svelte + TailwindCSS + DaisyUI ) => https://coreproject-db7l6gmf0-baseplate-admin.vercel.app/

**Comment by AKindWorld** [comment]
Well done! This looks amazing and is really smooth performance wise too.

Continuing on with the Svelte route is the best option, so full steam ahead!

There are some very small design tweaks that could be adjusted here & there, but since none of those are important, I'll make a list of those later. As for now, we can move on to the next part i.e. the Library - one of the best & most important parts of the project.

Btw, can you add the options to the preferences dropdowns? or would you do that later on? No worries either way though.

Just one thing - can you update this `border color` RGB value to 255 112 129 [a lighter variant]?

image

Great work btw! Really really good job :)

^^

**Comment by baseplate-admin** [comment]
> Just one thing - can you update this border color RGB value to 255 112 129 [a lighter variant]?

Would you mind telling me the color from [tailwind color palette](https://tailwindcss.com/docs/customizing-colors) ? Cause if we use non-tailwindcss color variables it will increase the CSS :) 

For now lemme roll with 700

> Btw, can you add the options to the preferences dropdowns? or would you do that later on? No worries either way though.

Preferences to dropdown ? Which node are we talking about 👀 ?

**Comment by AKindWorld** [comment]
Yup looks great! 300 looks good to me. Well done on implementing the splash screen too :) 

Should I merge this PR now?

**Comment by baseplate-admin** [comment]
Yep. Lets merge this 

^_^

**Comment by baseplate-admin** [comment]
Btw @AKindWorld 

Have you started working on the landing page?

**Comment by AKindWorld** [comment]
ah, I have the thought process pretty much ready, but no- it's not yet designed yet. 

I was experimenting & working on the Video player page; so I'll probably move on to it after that. What's the priority sequence for the all the pages currently? @baseplate-admin 

^^

**Comment by baseplate-admin** [comment]
I will finish the mainhero page in around a week. After that i will start working on the AnimeDetails Page. After that login page....

**Comment by baseplate-admin** [comment]
Btw we should design the landing page first because it will attract more people ( and more contributors )

**Comment by baseplate-admin** [comment]
So in this sense

Lets make the landing page our priority ^_^

**Comment by AKindWorld** [comment]
> I will finish the mainhero page in around a week. After that i will start working on the AnimeDetails Page. After that login page....

Sounds good to me. I'll design the Login & Register pages after this then. Can those be modals or do we need to create single pages for them? or like we did before - single page for register & modal for login?

> Btw we should design the landing page first because it will attract more people ( and more contributors )

ah I see. Alrighty then, I'll do that too; no worries! I might need about a week of time though ;-;

^^

**Comment by baseplate-admin** [comment]
> ah I see. Alrighty then, I'll do that too; no worries! I might need about a week of time though ;-;

Take as long as you need. No need to rush stuff around.  I also have plenty of work that needs to be finished :D

**Pull request merged**
