### PR TITLE
[ `Frontend` ] : Library slide

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Hey @AKindWorld you need to redesign left slide :) 

If we go swiper route theres no pagination. ( mobile version looks like swiper bullets ) 

On the right side. Lemme see if we can fix it 👀

**Comment by baseplate-admin** [comment]
@AKindWorld Hey there,

I need the library slide images :) 

---

Thanks ^^

**Comment by AKindWorld** [comment]
Hi there!

Good work on the Library section so far.

> I need the library slide images

Ah for these ones, you can just use the original posters for each anime. And for the Continue watching part, you can use the images we used in earlier - Rising of the Shield Hero & Kaguya-sama.

> Allllsooo read [this](https://shouldiuseacarousel.com/)

Hmmm, interesting. I have been considering this for a while too, but unlike e-commerce/sales platforms, we have a lack of diverse content to show to users. UX wise, it also shields the user from too much information right at one grasp - unlike the use cases mentioned in there, our goal is not to feed the user with information or products - in hindsight, we're not selling anything, so it doesn't matter either way if users look at it or not; the library of anime remains the same. So, our use-case is a complete 180 from the ones mentioned there, which is how design usually is - very much subjective & use dependent.

If there's any reason to remove the carousel, I think it would be for performance. I have been considering alternate layouts for quite a while now, and I have some layouts in mind that would work even without a carousel to supplement it. In those cases, not much changes - just a handful of additions, the Library goes to top and a couple of deletions. Pros are that now performance should be improved by a lot, and the Library is at the top within reach. Cons are that the website won't look as great as before - although, I should be able to spice it up xD.

If you're willing to, then we may go that route as well. Lemme know which one you prefer (both performance & design wise). I can also make a basic prototype of the alt homepage if you want to consider looking at it before deciding ^^

[Also that website's carousel has been made to be frustrating - it's by design so users would get frustrated & ditch it.]

---

Ah also for the Library, feel free to build the pagination whichever way you can - I'll update the design according to that.

Good job so far! Well done :)

^^

**Comment by baseplate-admin** [comment]
> If there's any reason to remove the carousel, I think it would be for performance. I have been considering alternate layouts for quite a while now, and I have some layouts in mind that would work even without a carousel to supplement it.

Currently our performance is good enough. Look at some big sites like YouTube / Netflix / Facebook / Discord. All of them are built using slow Technologies. So people dont care if the underlying technologies are slow / bloated. 

> our goal is not to feed the user with information or products

I disagree on this. My goal was to make a site which would give videos supplemented by informations about the series. ( that's why we have an anime info section ) 
Hopping between MyAnimeList and 9Anime was always a nuisance to me. 

> If you're willing to, then we may go that route as well. Lemme know which one you prefer (both performance & design wise). I can also make a basic prototype of the alt homepage if you want to consider looking at it before deciding ^^

Its actually upto you. My talent for designing is not the best. But yes i do like your design a lot :) thats why i am trying to make a 1:1 copy of your design.

----

Wait i actually sent this to troll you 😂

**Comment by AKindWorld** [comment]
> Currently our performance is good enough. Look at some big sites like YouTube / Netflix / Facebook / Discord. All of them are built using slow Technologies. So people dont care if the underlying technologies are slow / bloated.

ah yup exactly so. Most people don't know what the site/app is built using, and don't care either way. Well, I'm half like that too lol.

> I disagree on this. My goal was to make a site which would give videos supplemented by informations about the series. ( that's why we have an anime info section )
> Hopping between MyAnimeList and 9Anime was always a nuisance to me.

Yep, you're right on this one - my end goal is to design something that can supplement this too. But what I mean is that the information we show users is not monetized/for sale, so it doesn't matter either way if they look at it or not. Typically in e-commerce/social networking sites, that's how the design psychology works - every information is monetized/ has social points, so if anything loses spotlight, they lose money/interaction. 

> Its actually upto you. My talent for designing is not the best. But yes i do like your design a lot :) thats why i am trying to make a 1:1 copy of your design.

Yep, for now, we'll stick to the OG layout - it looks better & in this current frontend, works better too. I also have separate plans for the alt layout I was talking about. Also thanks for using my designs; I'm glad. \\^o^/

> Wait i actually sent this to troll you 😂

ah haha - no worries though. But I kinda don't like these information site thingies that tell people that there's only one way around a problem, from their limited knowledge & perspective about that thing - design & art are all subjective, so seeing these stuff irks me up lol. Don't worry though - it was a nice troll xD

> But take a look at the current library slide. ^_^

Yup, extremely well done so far; I'll wait for you to finish the main parts before noting all the design tweaks & such. 

Latest deploy looks great :) 

^^

**Comment by baseplate-admin** [comment]
Hey @AKindWorld we might need a rework on the library section.  Please check the latest development build. Swiperjs hides overflown slides. Now we have 2 choices 

1. Use CSS only carousels.
2. Somehow modify the swiperjs to show overflown slides? ( i donno if this is possible though)
3. Modify the design a bit to acomodate swiperjs

Thanks :D i will wait for your feedback

> Yep, you're right on this one - my end goal is to design something that can supplement this too. But what I mean is that the information we show users is not monetized/for sale, so it doesn't matter either way if they look at it or not. Typically in e-commerce/social networking sites, that's how the design psychology works - every information is monetized/ has social points, so if anything loses spotlight, they lose money/interaction.

Ah i seee.

> But I kinda don't like these information site thingies that tell people that there's only one way around a problem, from their limited knowledge & perspective about that thing -

I watched people bashing on PHP so much that i now bash people who uses PHP ( and react too ) . Well xD

**Comment by AKindWorld** [comment]
ah I see - so for the Carousel problem, I think we can now move on to CSS only slides too, or even cards with horizontal scrolling/next-previous buttons. For animations, we can just use simple CSS transitions. 

ah since you mentioned r/webdev, is [this](https://www.reddit.com/r/webdev/comments/v1rjlk/how_do_nike_and_apple_make_such_smooth_and_touch/) possible in our case? 

While I can modify the design to accomodate swiper, it would hurt the UX by a lot since full-length slides isn't a good choice for smaller ones. Nor can we make too many columns, that way the design would become very cluttered.

> Ah i seee. Personally i have never used social media that much. That's why i donno their monetization scheme.

xD not much for me either.

> You have a talent mate. You have a bright future ahead of you ^_^

Thanks xD. Same for you too - you're the best & most knowledgeable developer that I've worked with ^^

> Btw we might need a user guide to explain all the features to the users.

Yep, I'll implement it in the UI itself; visual cues & tips go a long way too. After that, we might need some test runs too to understand my design flaws :P.

> Would you mind switching the base-100 color to something a bit dark? In my opinion our current site has a bit too much contrast.

Ah yup, about this one too - I have some plans. Once we have finalized the current site frontend, I might experiment with themes quite a bit - basically with some predefined color palettes (an example would be like TachiJ2K). Which is why I don't wanna do anything right now - changing one color in the palette is a lot of work, especially mid development, so if possible, I'd like to deal with it later.

Thanks for reading!

**Comment by baseplate-admin** [comment]
> ah since you mentioned r/webdev, is this possible in our case?

This is exactly what i mean by CSS only slides  ^_^

**Comment by baseplate-admin** [comment]
@AKindWorld please review if the current implementation is to your liking :D

**Comment by AKindWorld** [comment]
Hi! sorry for the delay ;-;

Good job on the carousel! I think now swiper looks great too - so we can continue with it. Well done on making swiper do the impossible xD

There are some small CSS stuff here & there that can be improved, but I'll point those out after you finish most of the work. 

Btw, do you mind if I open a new issue regarding the design of Anime Info page? It's mostly for your reference since adding sticky notes on the Figma files is becoming a bit cluttered (also since I redesigned it completely, it might become confusing). I also wanna ask for your opinions on certain stuff there. If you don't have any problems, I might name it something like - [`Design`] Anime Info page

Great work! Good day ahead :)

^^

**Comment by baseplate-admin** [comment]
> Btw, do you mind if I open a new issue regarding the design of Anime Info page? It's mostly for your reference since adding sticky notes on the Figma files is becoming a bit cluttered (also since I redesigned it completely, it might become confusing). I also wanna ask for your opinions on certain stuff there. If you don't have any problems, I might name it something like - [Design] Anime Info page

Feel free :D. The [`Design`] Tag sounds good :D :D

**Comment by baseplate-admin** [comment]
Btw @tanimsk you should invest some time into this project. I know you have free time to watch stufd.

**Comment by AKindWorld** [comment]
> Would you mind replying to this? https://github.com/baseplate-admin/CoreProject/pull/427#issuecomment-1194480501

Yup - the swiper version; so [the 2nd one](https://coreproject-o8xnhv73j-baseplate-admin.vercel.app/).

Thanks btw!

^^

**Comment by baseplate-admin** [comment]
Btw i have 2 more questions

1. From where do you usually get images? 
2. Do you think the library slide looks okay on desktop?


Thanks ^=°

**Comment by baseplate-admin** [comment]
Btw i have 2 more questions 
1. From where do you usually get images? 
2. Do you think the current library slide looks okay on desktop?

Thanks °=^

**Comment by AKindWorld** [comment]
> From where do you usually get images?

Depends on the content. I usually just do a search for the anime and filter out the image/poster accordingly. Most of the times, I find a good fit within a bit - I usually try for official images, if it's available. 

> Do you think the current library slide looks okay on desktop?

Pretty much; some stuff can be resized accordingly here & there, but I'll wait for you to finish it before commenting. 

Here's a screenshot of how it looks on my screen:

image

At most, we need to resize the card/tiles a bit and adjust spacing/padding, and it'll look & work great. Some stuff would also change once you add the My List items.

^^

**Comment by baseplate-admin** [comment]
Hey @AKindWorld ,

We need to address the contrast issue on other elements.

image

See the information tab?

**Comment by AKindWorld** [comment]
Heyo!

Yup, I'm working on fixing the component contrast issues in the design files. It's a bit tricky honestly but I might figure something out.

---

About the Library's contrast issues, I have a couple of suggestions that I tested myself:

Currently it looks like this:

image

Here's how it should look after:

image


1. `Latest Episodes` text heading to the same font size as `Continue Watching` & `My List`. Since I'm dealing with static values, I used 1.875 rem.

2. For the background, set the `bg-opacity` parameter to 0 completely. Instead, use a `linear-gradient` parameter alongside the url value. The background-image value is:
`background-image: linear-gradient(90deg, rgb(7 5 25 / 92%) -1.41%, rgba(7, 5, 25, 0.1) 100%), linear-gradient(180deg, rgba(7, 5, 25, 0) -16%, rgb(7 5 25 / 90%) 95.81%), url(poster_url.format);`. (This value is only for the Latest Episodes image items)

3. Add a `border` parameter to all the image items. The value is: `border: 1px solid #070519`.

4. In the `Continue Watching` section, again add in a linear gradient value: 
`background-image: linear-gradient(90deg, rgb(7 5 25 / 92%) -1.41%, rgba(7, 5, 25, 0.1) 100%), linear-gradient(180deg, rgba(7, 5, 25, 0) -16%, rgb(7 5 25 / 90%) 95.81%), url(poster_url.format);`. 

5. Also, in Continue Watching section, make the swiper width value to `30vw` for larger screens.

6. [Optional] Is it possible to make swiper a bit more responsive to scroll? Like more scroll > scrolls more items; less scroll > scrolls less items. Currently it scrolls 1 value. 
If that's not possible, can you make it scroll 5 items on one scroll? That way, the amount of swiper dots also decreases to 1/5th the value. No worries if that's not possible though.

---

Overall, great work on the Latest Episodes section! Also on the Anime titles, posters & episodes. Once you make more changes, I'll point out the styling for Continue Watching & My List. 

Btw, for My List, can you make a scrollable card list with hoverable next/previous arrows. If you need a reference design, I'll make a rough one and send it here. Let me know if you need it.

Once again, great job!
Good day to you!

^^

**Comment by baseplate-admin** [comment]
Lemme clean the code base a little bit before commenting :D

**Comment by AKindWorld** [comment]
Yup, thanks! This looks all good now for the finished sections.

> You fiddled with the CSS ?

haha yup - that's the only way for me to test stuff on the real thing xD

> But lets not do it. Because it will unnecessarily tank performance. With almost 0 benefit?? ( is there any benefit ). Also mind that we have 40+ slides

Alrighty no worries - there's currently not much to gain from it, so it's all good.

---

Just another issue I noticed on my laptop's screen is the padding is a bit low on the sides. Kinda looks like this: 

image

Can you just increase the left & right padding/margin a bit further?

Great job so far!

^^

**Comment by baseplate-admin** [comment]
> Can you just increase the left & right padding/margin a bit further?

Currently it is 5 .

So should i jump to 6 or 8 ?

**Comment by baseplate-admin** [comment]
@AKindWorld do you have any more suggestions?

**Comment by AKindWorld** [comment]
Latest Episode section looks pretty good. Well done on fixing the scroll! Just another thing - can you revamp the dots pagination? You can either remove them completely or go for a vertical fixed slider scroll, whichever is possible & easier. The dots look good, but it may cause problems in the future (when the number of entries is bumped up) and also don't side in with the pagination logic. But there's no hurry for this. Take your time :)

and can you re-add the `text-white` class back? The current text color (primary, I think?) is a bit too unsaturated for all the body & heading texts.

No more suggestions. Well done ^^

**Comment by baseplate-admin** [comment]
Hi @AKindWorld ,

Sorry for the delay. I needed some time alone ( I did bad in my math exam )

Now back to topic,

> Latest Episode section looks pretty good. Well done on fixing the scroll! Just another thing - can you revamp the dots pagination? You can either remove them completely or go for a vertical fixed slider scroll, whichever is possible & easier. The dots look good, but it may cause problems in the future (when the number of entries is bumped up) and also don't side in with the pagination logic. But there's no hurry for this. Take your time :)

I have removed the pagination for now. Vertical scrollbar is more trouble than what its worth. I will re design it if there is another need for it :D 

> and can you re-add the text-white class back? The current text color (primary, I think?) is a bit too unsaturated for all the body & heading texts.

Opps sorry, i was doing some tweaking, i forgot to push it to master. It should be fixed now :D 

> 8 sounds fine to me; without negative space, it would look too cluttered for our current layout. I'll tell you later if we need to change it back.

8 it is then :D 

---


Thanks for your review :D

**Comment by baseplate-admin** [comment]
Check out my new code

```typescript

    const kokoro_word_color_map: {
        [key: string]: string;
    } = {
        "-": "white",
        a: "white",
        c: "white",
        h: "white",
        k: "white",
        n: "white",
        o: "yellow",
        r: "white"
    };

    const tailwind_color_map: {
        [key: string]: string;
    } = {
        white: "text-white",
        yellow: "text-warning"
    };


{#each "kokoro-chan".split("") as word}
            <span class="inline-flex {tailwind_color_map[kokoro_word_color_map[word] ?? '']}">
                {word}
            </span>
{/each}
```

**Comment by baseplate-admin** [comment]
( hi @AKindWorld , gentle ping incase you forgot about this :D )

**Comment by AKindWorld** [comment]
Ah sorry for the delay in responding; I had it in mind but didn't get time to respond back. (I did get a bit of time but I only added some stuff to the Figma files since I had a sudden idea for some of the new mockups)

Well done on fixing those stuff, pagination looks pretty good now, and white's back xD


Haha, for the new code, I take it that it's for the error page _kokoro-chan_, right? well done xD 

_let's leave out the fact that the code logic goes completely over my head_

The error pages look and work great too!

As for next steps, what're you going to focus on next? Adding posters to the My List section, or moving on to the next section - Explore?


Great work so far!
Good day to you :)

^^

**Comment by baseplate-admin** [comment]
> Ah sorry for the delay in responding; I had it in mind but didn't get time to respond back. (I did get a bit of time but I only added some stuff to the Figma files since I had a sudden idea for some of the new mockups)

No worries ;D 

> Well done on fixing those stuff, pagination looks pretty good now, and white's back xD

Sorry for the weird neutral font

> Haha, for the new code, I take it that it's for the error page kokoro-chan, right? well done xD

Yep, I have perfected it :D 

> *let's leave out the fact that the code logic goes completely over my head*

*no wonder i want to destroy humanity*

> As for next steps, what're you going to focus on next? Adding posters to the My List section, or moving on to the next section - Explore?

For now i will add some mock data to simulate the Library section. Also i am thinking of doing anime page next instead of doing the explore section. I need a new page to test some stuff around

**Comment by baseplate-admin** [comment]
> Ah sorry for the delay in responding; I had it in mind but didn't get time to respond back. (I did get a bit of time but I only added some stuff to the Figma files since I had a sudden idea for some of the new mockups)

No worries ;D .. Lemme check the figma file

> Well done on fixing those stuff, pagination looks pretty good now, and white's back xD

Sorry for the weird neutral font

> Haha, for the new code, I take it that it's for the error page kokoro-chan, right? well done xD

Yep, I have perfected it :D 

> *let's leave out the fact that the code logic goes completely over my head*

*no wonder i want to destroy humanity*

> As for next steps, what're you going to focus on next? Adding posters to the My List section, or moving on to the next section - Explore?

For now i will add some mock data to simulate the Library section. Also i am thinking of doing anime page next instead of doing the explore section. I need a new page to test some stuff around.


---

Also on a more serious note, I am planning to rewrite backend. The current implementation is not to my liking and the framework we are using `django-rest-framework` is not [looking to adopt official features](https://github.com/encode/django-rest-framework/pull/8445) and [lackluster support for nested serializers](https://github.com/encode/django-rest-framework/pull/1048) and [is never going to support NoSQL](https://stackoverflow.com/questions/41406219/django-with-nosql-database) and [I dont know when async support will be available](https://docs.djangoproject.com/en/4.0/topics/async/#performance). Personally i am tired of DRF and [comments like this make it worse](https://github.com/encode/django-rest-framework/discussions/8110#discussioncomment-1120770). 

Lack of nested serializer is why we have this type of code :
```python
 def create(self, validated_data):
        instance, created = AnimeCharacterModel.objects.get_or_create(
            mal_id=validated_data["mal_id"],
            name=validated_data["name"],
            character_image=validated_data["character_image"],
        )

        AnimeInfoModel.objects.get(pk=self.context["anime_id"]).anime_characters.add(
            instance
        )
```
in
1. https://github.com/baseplate-admin/CoreProject/blob/master/backend/apps/anime/serializers/anime_character.py
2. https://github.com/baseplate-admin/CoreProject/blob/master/backend/apps/anime/serializers/anime_producer.py
3. https://github.com/baseplate-admin/CoreProject/blob/master/backend/apps/anime/serializers/anime_studio.py
4. https://github.com/baseplate-admin/CoreProject/blob/master/backend/apps/anime/serializers/anime_theme.py

But its a big rework ( since backend is considered feature complete i didn't want to waste time there ).So i want to reuse most of the codes that i wrote and was looking for something nicer and i found `django-ninja`. So after a while i might take break from frontend to refractor the backend :D 

So in this sense we have a few choices.


1. Spring-Boot ( Java. I am looking into this for a while. But i have never written any java codes. So the implementation will take quite a while. **around 5-6 month** )
5. FastApi ( **My preferred choice** )
6. Flask ( Same as FastApi but **has an [admin panel](https://pypi.org/project/Flask-Admin/)** )
7. NestJS ( Looking into this but meh. But this has typescript and a build system support ( both of which are awesome features.. Also we can do Server Side Rendering of svelte components. Which removes the `svelte-kit` package ) )

All of the above projects require an admin panel ( except maybe flask ). Which means more work on you. Also if we make the custom admin panel we can show cool stats like [this](https://preview.themeforest.net/item/epic-ui-angular-admin-template-hr-management/full_screen_preview/34000161)
Or we can go with 

1. `django-ninja` ( which is still a new project )

**Comment by AKindWorld** [comment]
Heyo!

> For now i will add some mock data to simulate the Library section. Also i am thinking of doing anime page next instead of doing the explore section. I need a new page to test some stuff around.

Yup, sounds good to me. Anime Info page is almost ready too, so I have no problems there.

> Also on a more serious note, I am planning to rewrite backend. The current implementation is not to my liking and the framework we are using django-rest-framework is not https://github.com/encode/django-rest-framework/pull/8445 and https://github.com/encode/django-rest-framework/pull/1048 and [is never going to support NoSQL](https://stackoverflow.com/questions/41406219/django-with-nosql-database) and [I dont know when async support will be available](https://docs.djangoproject.com/en/4.0/topics/async/#performance). Personally i am tired of DRF and https://github.com/encode/django-rest-framework/discussions/8110#discussioncomment-1120770.

Ah I see; no worries, feel free to take your time. I need quite a bit of time too in order to sync up the design mockups & design system, so I don't mind either.

> So in this sense we have a few choices.

Hmm. I think you can choose any one of those; if we need to craft a custom admin panel, then I can do that for sure - no worries. I'll keep the design lighter in that part too, and we can probably expand as we need to. And if the framework does come with a built-in one, then that's good too. 

All in all, I think they all sound good, you can choose whichever you like most, and whichever is the most stable for the future. Honestly, so long as we can make something good, it doesn't matter how long it takes.

Just another thing - in the future, we will need to make hover tooltips for the anime entries (kinda like some other sites have too - AniList entries are a good example) - I didn't design anything regarding that yet since I'm not sure of how much customization we can do on it and performance impacts on the site overall. Do you know or have any resource on how much feature-rich we can make those without a noticeable performance impact? (like is there something built-in or some sort of other library thingie for those?) I don't know much about it, so I didn't wanna design it yet.

Thanks a lot for your work!
Good day!

^^

**Comment by baseplate-admin** [comment]
> Hmm. I think you can choose any one of those; if we need to craft a custom admin panel, then I can do that for sure - no worries. I'll keep the design lighter in that part too, and we can probably expand as we need to. And if the framework does come with a built-in one, then that's good too.

Thats the problem. No framework except Django has a good built in admin panel.

> All in all, I think they all sound good, you can choose whichever you like most, and whichever is the most stable for the future. Honestly, so long as we can make something good, it doesn't matter how long it takes.

Umm yea. I have grown tired of how stuffs are handled. But lemme see if i can preserve some codes.

> Just another thing - in the future, we will need to make hover tooltips for the anime entries (kinda like some other sites have too - AniList entries are a good example) - I didn't design anything regarding that yet since I'm not sure of how much customization we can do on it and performance impacts on the site overall. Do you know or have any resource on how much feature-rich we can make those without a noticeable performance impact? (like is there something built-in or some sort of other library thingie for those?) I don't know much about it, so I didn't wanna design it yet.

We can use [daisyui ](https://daisyui.com/components/tooltip/) for tooltips or we can also use [tippy.js](https://atomiks.github.io/tippyjs/) ( but tippy.js is on the heavier side )

**Comment by baseplate-admin** [comment]
hey @AKindWorld take a look,

But i used tint in the mylist section. should i do background shadow there too ? ( its a bit hard this time cause we dont have access to the card element 

Thanks :D

**Comment by AKindWorld** [comment]
Yup checked it; well done on the entries.

About the tint part, yup, it's okay if you use a tint on these entries - but maybe use a higher value like `#070519` at 70%.

Also, the text colors are somehow not white again (only on the My List entries). Can you fix those?

Good job!

^^

**Comment by baseplate-admin** [comment]
> About the tint part, yup, it's okay if you use a tint on these entries - but maybe use a higher value like #070519 at 70%. (nvm, it's dark enough with the White text color)

Done .. lets merge this

**Review by AKindWorld — APPROVED** [review]
Great work on this! 

^^

**Pull request merged**
