### PR TITLE
[`Frontend`] : Add more slides

### PR DESCRIPTION
**Pull request by baseplate-admin**
Hey @AKindWorld ,

I am getting sooo much excited for this PR. Please please take a look. And thanks for your awesome work

### CODE REVIEW

**Comment by AKindWorld** [comment]
Aha yup! good going so far :)

Lemme add the other entries quickly.

**Comment by baseplate-admin** [comment]
Done @AKindWorld

**Comment by baseplate-admin** [comment]
Everything except the tags work ( i will check that tomorrow ) 

For now merge this please :D

**Comment by baseplate-admin** [comment]
https://codesandbox.io/s/0xr0rprx10?file=%2Fsrc%2Fslider.js

**Comment by AKindWorld** [comment]
Well done! Looks amazing!

Just another request - I updated the BG Images for Hyouka, Konosuba, Jujutsu Kaisen, Hamefura & Shield Hero. The new links are below the current links in the Figma files but I'm still linking them here for convenience.

- [Hyouka](https://files.catbox.moe/7npbvm.jpg)
- [Konosuba](https://files.catbox.moe/tb721n.png)
- [Jujutsu Kaisen](https://files.catbox.moe/sxyb4o.jpg)
- [Hamefura](https://files.catbox.moe/5k4yb4.jpg)
- [Shield Hero](https://files.catbox.moe/hxphzq.jpg)

The image sizes are bit higher but it looks really amazing on larger screens (no more pixelization). Also all of them are official artworks & free for use.

I know that larger image files would cause an issue but for now, use these. We'll have to figure out an workaround (probably using the tip or optimizing it ourselves).

And everything works fine! Well done xD

Good day to you!

^^

**Comment by baseplate-admin** [comment]
Fixxed. 

But check my reply in the other thread :D 


---

Also please merge this issue

---

Thanks :D

**Review by AKindWorld — APPROVED** [review]

**Comment by baseplate-admin** [comment]
> Yup, the final deployment looks amazing! Well done on your work!

All thanks to you... If it werent for you nothing would have been possible :D 

> I'll merge this then. On another note - would you be starting the next section after this? Search & Preferences?

#393 is here 🗡️ 

---

> Once again, great work!

Same to you :D thanks for all the reviews

**Comment by baseplate-admin** [comment]
Also @AKindWorld, Sorry for this ping. But would you mind checking [this message on discord?](https://discord.com/channels/@me/958266195654639646/993479285220315136)

**Pull request merged**
