### PR TITLE
[ `Frontend` ] : Modify `MainHero`

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
Pinging @AKindWorld 

Do you think the padding on left is a bit too wide?

SmartSelect_50_Firefox Nightly

**Comment by AKindWorld** [comment]
> Do you think the padding on left is a bit too wide?

Ah yes, just a bit, but yup. Btw, is this for the mobile view? If so, then some elements would stay hidden and the font size would be greatly decreased as well.

But other than that, good job!

**Comment by baseplate-admin** [comment]
>     Ah yes, just a bit, but yup. Btw, is this for the mobile view? If so, then some elements would stay hidden and the font size would be greatly decreased as well.

**Comment by baseplate-admin** [comment]
@AKindWorld check now. But we have a problem. We can have a progressbar / bullet. So lets stick to one :D . ( unless i am missing something as swiper exposes one type of element )

**Comment by baseplate-admin** [comment]
I am looking for the pagination review :P The color seems a bit off

**Comment by baseplate-admin** [comment]
Need #354 to be fixed :D

**Comment by baseplate-admin** [comment]
Hey @AKindWorld  check the desktop UI. does every element look okay-ish?

**Comment by baseplate-admin** [comment]
Mobile version is done too ( ignore the more words part ( will fix it in a bit )

**Comment by baseplate-admin** [comment]
> ah sorry - which frame was it from? sorry I got confused xD.

[Here you go](https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?node-id=690%3A686)

---

Another small nitpick.
can you increase the button size in there to around 62px ?

**Comment by baseplate-admin** [comment]
> Yup, so Desktop UI looks good to me. Only thing is that, as I mentioned a few days earlier, I'm working on a sidebar UI which I'll add to the mockup soon, but no worries - you can add that later too.

Okay ;D But it comes a bit later i guess :P

**Comment by AKindWorld** [comment]
> Umm xD sorry i cant figure out the cursor chat thingy

no worries. I think it should appear as you type `/` in the keyboard. Or right click and click on Cursor chat works too

But no worries even if it doesn't work xD

**Comment by baseplate-admin** [comment]
@AKindWorld  please check the [mantine docs](https://mantine.dev/core/button/#customize), would you mind adding a bit more text / something along these lines ? Otherwise you might need to increase size

**Comment by baseplate-admin** [comment]
@AKindWorld Please answer this [question](https://github.com/baseplate-admin/CoreProject/pull/348#issuecomment-1160611808)

**Comment by baseplate-admin** [comment]
Final work is done ;P 

Please take a look at the deploy files

**Comment by baseplate-admin** [comment]
> About the mobile UI, it looks good too. Only add the swiper bullets if possible.

Done

**Comment by baseplate-admin** [comment]
>  Ah yeah, so for the desktop UI. Hmm - I haven't decided on any particular values since my designs are all static values, and the real UI may scale differently from mine; in the design files, the padding is 20px, but I think we might need to use percent values in here. You can try 1%vw as the padding and see how that looks like. If it doesn't look good, bump it by 0.25% each time and see if that works.

Done

**Comment by baseplate-admin** [comment]
> Also, a whole thing about Swiper, add in a 10s animation for each slide. 

Done

**Comment by baseplate-admin** [comment]
> So, yup, all good. Only one thing I'd suggest is to make the swiper slide indicator/bullets in the center of the page (if possible). 
Done

**Comment by baseplate-admin** [comment]
> Another thing - for the scroll below text, I'd suggest you to use a off-white tint if possible. Or white with a 60% opacity. Whichever works.

Done

**Comment by baseplate-admin** [comment]
> And same for this - if possible, change the bg color of these things to #070519 [Azure/Blue 10, I think].

Done

**Comment by baseplate-admin** [comment]
Anything more you think is wrong ( check mobile too )

**Comment by AKindWorld** [comment]
Okay so some more too - hope you don't mind.

image

1. Is it possible to make the H1 texts larger? It seems Mantine has their own text scaling sizes, but the designs are made with a different sizing. It would be best if we could use [our own scaling](https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?node-id=584%3A1313), but no worries if we can't.
2. The color for the description text too, if possible - please change it to a tint of white - around 5/6 should work.
3. Also, if possible, a little bit of spacing between the sub-details (year/season/etc text) & the description text would be nice. 
4. The color for the buttons is currently something like... #FAD050... Elaine[9], I think. Although it looks pretty good, I'd prefer #E3BD49. Elaine[10] - I think. For both the small button's fill and the longer button's outline.
5. For some reason, the swiper indicators are still not centered for me :(


Sorry for making you work so much. Please feel free to take your time on this ^^

**Comment by baseplate-admin** [comment]
> Is it possible to make the H1 texts larger? It seems Mantine has their own text scaling sizes, but the designs are made with a different sizing. It would be best if we could use [our own scaling](https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?node-id=584%3A1313), but no worries if we can't.

We can use our own sizes :P Check last commit

**Comment by baseplate-admin** [comment]
image
 This is how it looks for me

**Comment by baseplate-admin** [comment]
image
Does this look okay?

**Comment by baseplate-admin** [comment]
> Also, if possible, a little bit of spacing between the sub-details (year/season/etc text) & the description text would be nice.

Done

**Comment by baseplate-admin** [comment]
> The color for the description text too, if possible - please change it to a tint of white - around 5/6 should work.

Do you think we can do shades of white ?

**Comment by baseplate-admin** [comment]
> The color for the buttons is currently something like... #FAD050... Elaine[9], I think. Although it looks pretty good, I'd prefer #E3BD49. Elaine[10] - I think. For both the small button's fill and the longer button's outline.

Umm is it possible not to do this ( cause mantine does some weird stuff in the background )

**Comment by baseplate-admin** [comment]
All finished.

@AKindWorld  looking for final review

**Comment by baseplate-admin** [comment]
image


GIthub is bugging out for me XD

**Comment by AKindWorld** [comment]
Looks pretty good for me! Well done :)

There's some things we can fix/work on later on - animation timings/animation-halt-on-hover/button-hover values and also the image formats.

For now, this looks all good to me.

Oh just one thing - this text isn't in Kokoro Bold; looks like it inherits the system font. Would be great if you could fix it!

image


Once again, well done :) Great work!

Have a great day ahead.

**Comment by baseplate-admin** [comment]
> Oh just one thing - this text isn't in Kokoro Bold; looks like it inherits the system font. Would be great if you could fix it!

Done

**Comment by baseplate-admin** [comment]
> Once again, well done :) Great work!

You are doing the main review tho 💀 

> Have a great day ahead.

Same to you

**Comment by baseplate-admin** [comment]
If everything looks okay please merge this PR

**Comment by AKindWorld** [comment]
Well done!

Also, looks like the apostrophe bug is back ;-;

and Github seems to be bugging out for me too (￣__,￣ )

**Comment by baseplate-admin** [comment]
> Github seems to be bugging out for me too (￣__,￣ )

This is what happens when companies get bought by an evil tech corporation

**Comment by baseplate-admin** [comment]
> Also, looks like the apostrophe bug is back ;-

I hate JS

**Comment by AKindWorld** [comment]
haha but you're doing most of the work though; so well done :)

Now it looks all good; ready for merging! A total of 55 commits right?

**Comment by baseplate-admin** [comment]
> Now it looks all good; ready for merging! A total of 55 commits right? 

Yep. Squash it 📦

**Comment by baseplate-admin** [comment]
> haha but you're doing most of the work though; so well done :)

just have some time before school kicks in

**Pull request merged**
