### PR TITLE
[ `Frontend` ] : Fix timer

### PR DESCRIPTION
**Pull request by baseplate-admin**
@AKindWorld  take a look

### CODE REVIEW

**Comment by baseplate-admin** [comment]
This is as smooth as it can get sadly :|

**Comment by baseplate-admin** [comment]
Mantine is not meant to be smoother than this i am afraid :/ but still i will take another look

**Comment by baseplate-admin** [comment]
For now lets nerge this :D

**Comment by AKindWorld** [comment]
Okay looks much better to me. Just a small suggestion (feel free to work on it later tho)

1. Is it possible to enable infinite rotation? Currently after Slide 3, it doesn't automatically move on to Slide 1 and the progress bar gets stuck instead. Not that it's much of an issue though.

Another question - is it possible to manually pause the slideshow/carousel-rotation (like by using a button/hover state)?

That's all! 
I'll merge this then!

^^

**Comment by baseplate-admin** [comment]
> Another question - is it possible to manually pause the slideshow/carousel-rotation (like by using a button/hover state)?

Its very possible. But i didn't implement it. Do you want to implement it ?

**Comment by baseplate-admin** [comment]
> Is it possible to enable infinite rotation? Currently after Slide 3, it doesn't automatically move on to Slide 1 and the progress bar gets stuck instead. Not that it's much of an issue though.


Fixed

**Comment by baseplate-admin** [comment]
But in case of suggestions like [this](https://github.com/baseplate-admin/CoreProject/pull/388#issuecomment-1172004661) .

Please open them in a issue :P 

That way i might not miss that


----


Thanks :D 

I wish you a good day

**Comment by AKindWorld** [comment]
Ah my bad!

Let's discuss this in a new issue then - I'll make one to cover for all of the Carousel stuff.

^^

**Comment by baseplate-admin** [comment]
> Ah my bad!

Ahh no worries. For now lets keep the discussion in #390

**Pull request merged**
