### PR TITLE
[ `Frontend` ] : Add `BackgroundImage` from mantine

### PR DESCRIPTION
**Pull request by baseplate-admin**
@AKindWorld

Do you notice any changes?

### CODE REVIEW

**Comment by AKindWorld** [comment]
uhh- Visually... not really.

In the code files, quite a bit xD. Judging from the naming, I take it that you're using [this](https://mantine.dev/core/image/#backgroundimage-component) to render the images (& content on top of it) now?

Should I merge this right now or later?

---

ah- also another thing - it's a bit out of topic but I didn't want to open an issue for such a minor thing - how will we be handling Button hover states? Is there anything built-in in Mantine? I know it already has a somewhat color-change hover state for some buttons (ex: the Details button). 
I don't think all buttons need it, but a better hover animation (ex: on the Watch button) would be a nice touch (just something like filling up the svg & transitioning it would be great). Do we need to use custom CSS for that? Or is there some other way?

---

Good day to you! 

^^

**Comment by baseplate-admin** [comment]
>  I don't think all buttons need it, but a better hover animation (ex: on the Watch button) would be a nice touch (just something like filling up the svg & transitioning it would be great). Do we need to use custom CSS for that? Or is there some other way?

I am also unsure on this :| . For now lets skip it. We will swing at it after i finish doing more slides. And i brainstorm a bit more.

 > In the code files, quite a bit xD. Judging from the naming, I take it that you're using [this](https://mantine.dev/core/image/#backgroundimage-component) to render the images (& content on top of it) now?
 
 Yep. This stupid [react library](https://www.npmjs.com/package/@emotion/react) cant even do [whats its designed to do](https://github.com/baseplate-admin/CoreProject/blob/65d290d1af6e13cb5e2e8a78900dd626f9d05421/frontend/AnimeCore/components/swiper/MainHero.tsx#L195).
 
With each passing day. I am starting to lose more of my sanity. 

> Should I merge this right now or later?

About this. Would you please take a look at [this](https://discord.com/channels/@me/958266195654639646/991571156136120360) ?

---

> Good day to you!

Same to you ^=^

**Comment by baseplate-admin** [comment]
@AKindWorld take a look at last Deployment. 

Also please merge this

**Comment by AKindWorld** [comment]
Yup looks good to me! Well done :)

Just a couple of suggestions -

- There seems to be something wrong in the progress bar part since it currently shows this (shows 66.67% progress even on last slide; should be 100% technically...?):
CoreProjectCarouselSwitchGIF0001

On another note - do you think this progress bar can be made to show the active slide time instead of the slide number? I think that's a better use for it, and is what I originally intended as well.


-  This is not that much important so feel free to skip it if you wish to - can you edit the 2nd & 3rd slides info a bit? The following are the information for them
    - [Konosuba] `TV • 10 eps • Completed • Winter 2016 • Studio DEEN`
    - [Ajin] `TV • 13 eps • Completed • Winter 2016 • Polygon Pictures`


- Since we've got quite a bit of visitors coming now, I was thinking if we could put up an indicator in the site that this site is WIP and a link back to the this repo (since currently there's a one-way connection). 
I think we can use [this](https://mantine.dev/core/notification/) for it, although you can use something else too if you'd like to. This is just a suggestion though, if it's too much work or you think it might ruin something, feel free to disregard it.

> My goal is fulfilled. Now i can die happily.

Don't die though lol xD

> I am also unsure on this :| . For now lets skip it. We will swing at it after i finish doing more slides. ( also some more brainstorming )

Sure sure! If you need the button animations as a mockup, I can prepare them as well. Would take me just a couple of minutes.

> Also we got another watcher :D ( also another star too )

Yup great xD. We're close to 10 stars & 5 watching now (which is a pretty good accomplishment honestly). Also I'll update the Readme images & links in a while - it's a bit outdated now :P

I'll merge this in a while. Thanks a lot for your hard work!

^^

**Comment by baseplate-admin** [comment]
> There seems to be something wrong in the progress bar part since it currently shows this (shows 66.67% progress even on last slide; should be 100% technically...?):

This is what i am investigating :P 



----

Lemme fix this and i will get back to you

**Comment by baseplate-admin** [comment]
> Since we've got quite a bit of visitors coming now, I was thinking if we could put up an indicator in the site that [this](https://mantine.dev/core/notification/) site is WIP and a link back to the this repo (since currently there's a one-way connection).
I think we can use this for it, although you can use something else too if you'd like to. This is just a suggestion though, if it's too much work or you think it might ruin something, feel free to disregard it.

Got it. Gimme some time

**Comment by baseplate-admin** [comment]
> Since we've got quite a bit of visitors coming now, I was thinking if we could put up an indicator in the site that [this](https://mantine.dev/core/notification/) site is WIP and a link back to the this repo (since currently there's a one-way connection).
I think we can use this for it, although you can use something else too if you'd like to. This is just a suggestion though, if it's too much work or you think it might ruin something, feel free to disregard it.

Done. Take a look

**Comment by baseplate-admin** [comment]
>    TV • 10 eps • Completed • Winter 2016 • Studio DEEN
>    [Ajin] TV • 13 eps • Completed • Winter 2016 • Polygon Pictures

Fixed

**Comment by baseplate-admin** [comment]
> Sure sure! If you need the button animations as a mockup, I can prepare them as well. Would take me just a couple of minutes.

Its gonna be manual transition :'/

**Comment by baseplate-admin** [comment]
> There seems to be something wrong in the progress bar part since it currently shows this (shows 66.67% progress even on last slide; should be 100% technically...?):

This Just proves that i suck at math

**Comment by baseplate-admin** [comment]
> Don't die though lol xD

At this rate it wont be long fore me death

**Comment by baseplate-admin** [comment]
Also @AKindWorld  please answer [this](https://discord.com/channels/@me/958266195654639646/991628577911099462) too

**Comment by AKindWorld** [comment]
> Umm i am not getting what you mean. Can you send a picture? Where should i show time?

Ah sorry I should have shown it somehow - this is what I'm talking about: [Animation 1](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=1369%3A1185&node-id=1369%3A6802&viewport=-3684%2C3334%2C1.59&scaling=contain&starting-point-node-id=1369%3A6802) & [Animation 2](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=1369%3A1185&node-id=1369%3A8068&viewport=-3684%2C3334%2C1.59&scaling=contain&starting-point-node-id=1369%3A8068&show-proto-sidebar=1).

Basically it uses the progress bar to show the active slide time progress instead of the slide numbers progress - which is technically a better use for the progress bar and also UX-wise, lets the user know how long it is till it automatically switches to the next slide. Is making something like this possible? Otherwise we might need to set Autoplay off on hover for some elements in Swiper. Since currently it so happens that when you're reading stuff from one slide, it auto-switches to the next one randomly. So this is only one of the 2 solutions that look good visually (also cute short progress bars!) xD

If it can be done, feel free to do it in a different PR though (this one's got enough on it right now xD)

> Its gonna be manual transition :'/

ahh I see. Well no worries - let's have it on hold for the moment, we'll see about it later on.

> Yep. Lets hope this project gets more traction... :D

yep!

> This Just proves that i suck at math

nope!

> Though i have another request. Can you gimme 10 slides for the MainHeroSwiper? To make it look a bit more awesome?

Haha sure sure! I'll start working on it soon; but I might make it in the old Figma file (new one is out of pages and I don't want to crowd it up much). Just give me a while for this - shouldn't take too long.

> Done. Take a look

Yep well done! Just a suggestion - it seems like links doesn't work there, so you can do something like this: (use Blue [4] or Blue[6] for the color)

image

Also if possible, can you put it to the top of the page? If it's not possible though, feel free to leave it at the bottom.

---

Sorry for the delay in replying!

Good day to you! And thanks for all the work!

^^

**Comment by baseplate-admin** [comment]
Lemme get back to you in 5 hour :P

**Comment by baseplate-admin** [comment]
> Haha sure sure! I'll start working on it soon; but I might make it in the old Figma file (new one is out of pages and I don't want to crowd it up much). Just give me a while for this - shouldn't take too long.

But please send the Raw Image files too :)

**Comment by baseplate-admin** [comment]
@AKindWorld  i just pushed a big refractor. Take a look if i missed aynthing

**Comment by baseplate-admin** [comment]
> Basically it uses the progress bar to show the active slide time progress instead of the slide numbers progress - which is technically a better use for the progress bar and also UX-wise, lets the user know how long it is till it automatically switches to the next slide. Is making something like this possible? Otherwise we might need to set Autoplay off on hover for some elements in Swiper. Since currently it so happens that when you're reading stuff from one slide, it auto-switches to the next one randomly. So this is only one of the 2 solutions that look good visually (also cute short progress bars!) xD 

This is fixed

**Comment by AKindWorld** [comment]
Ah thanks! well done - one suggestion though:

can you make the animation smoother? I know my [Animation 1](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=1369%3A1185&node-id=1369%3A6802&viewport=-3684%2C3334%2C1.59&scaling=contain&starting-point-node-id=1369%3A6802) prototype has it like that, since it's a drawback of Figma - without specialized plugins or lots of graph-time-dampness-mass tinkering, it looks pretty stiff & kinda broken.

I could get the [Animation 2](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=1369%3A1185&node-id=1369%3A8068&viewport=-3684%2C3334%2C1.59&scaling=contain&starting-point-node-id=1369%3A8068&show-proto-sidebar=1) prototype right with some tinkering but unfortunately, its transition is pretty short. 
[In the Figma file, press R to restart the animation since it's one way only.]

This is what I mean: 

CoreProjectCarouselProgress0001

The transition should be like this but longer (8s or 10s depending on our carousel switch time).

I think just for this one, you can use a custom CSS transition too - if all else fails. This is one of the places where custom CSS would be a pretty good fit, only if there's no other way to do it. But feel free to take your time on it. I should have the other 7 carousel layouts ready sometime in the next 12-18 more hours (couldn't get much time earlier).

Other than that, it's all good (timing + visually).

^^

**Comment by baseplate-admin** [comment]
> can you make the animation smoother? I know my [Animation 1](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=1369%3A1185&node-id=1369%3A6802&viewport=-3684%2C3334%2C1.59&scaling=contain&starting-point-node-id=1369%3A6802) prototype has it like that, since it's a drawback of Figma - without specialized plugins or lots of graph-time-dampness-mass tinkering, it looks pretty stiff & kinda broken.

This is hard to do for now. We need [this](https://github.com/amrlabib/react-timer-hook/issues/87) issue to be solved first :)

**Comment by baseplate-admin** [comment]
> I think just for this one, you can use a custom CSS transition too - if all else fails. This is one of the places where custom CSS would be a pretty good fit, only if there's no other way to do it. But feel free to take your time on it. I should have the other 7 carousel layouts ready sometime in the next 12-18 more hours (couldn't get much time earlier).

Got it. Thanks :D

**Comment by baseplate-admin** [comment]
Fixed almost everything :D

**Comment by baseplate-admin** [comment]
I have this [repo](https://github.com/baseplate-admin/react-timer-hook) to get some things fixed :) 

But merge this Pull Request

**Comment by AKindWorld** [comment]
> This is hard to do for now. We need https://github.com/amrlabib/react-timer-hook/issues/87 issue to be solved first :)

Ah alrighty I see. Don't worry - feel free to take your time.

> But merge this Pull Request

Should I do it now or wait till for other 7 carousel entries? Or would you add those in a separate PR?

Good day to you :)

^^

**Comment by baseplate-admin** [comment]
> Should I do it now or wait till for other 7 carousel entries? Or would you add those in a separate PR?

Another PR sounds good :)

**Comment by AKindWorld** [comment]
Alrighty then!

Merging this one \\^o^/

**Comment by baseplate-admin** [comment]
image


Nice one you have here XD

**Pull request merged**
