### PR TITLE
Add error pages

### PR DESCRIPTION
**Pull request by baseplate-admin**
@AKindWorld You are up :D

### CODE REVIEW

**Comment by baseplate-admin** [comment]
IF you cant run django :) And get this error page :) I will send you some SS

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
For now do not merge
i will have to add the fonts and do the coloring on text

**Comment by baseplate-admin** [comment]
And also we need 2 more pages

`500`
`400`

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
image

**Comment by baseplate-admin** [comment]
@AKindWorld

**Comment by baseplate-admin** [comment]
image

**Review by AKindWorld — APPROVED** [review]
Error pages all done! Good job!

Although let's hope our users don't have to see those too much xD

**Comment by baseplate-admin** [comment]
😂 
Agreed

**Pull request merged**
