### PR TITLE
[ `Frontend` ] : Fix slider

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
@AKindWorld does this Pull request fixes the problem?

**Comment by AKindWorld** [comment]
ah so sorry for the delay in responding.

Yup it works perfectly now - infinite scroll & pause on description hover. Really well done!

I think the Carousel is now very much ready & feature-rich, so feel free to move on to the next section.

I had been working on the seven extra Carousel entries but then got a bit busy. I'll finish up right now and you can add them too, if you wish to. Sorry for the delay. [Link to all the Carousel entries](https://www.figma.com/file/knyOkHUChnJpsAsmuILhOk/Core-Project-%5BLegacy%5D?node-id=1113%3A2181) [so far 6 done, 4 left]

also, should I merge this issue? or would you add the extra entries on this one?

Good day to you

^^

**Comment by baseplate-admin** [comment]
> ah so sorry for the delay in responding.

No worries... I am bit busy myself.

> Yup it works perfectly now - infinite scroll & pause on description hover. Really well done!

Though there are countless patch that are somehow holding this all together 🎃

> I had been working on the seven extra Carousel entries but then got a bit busy. I'll finish up right now and you can add them too, if you wish to. Sorry for the delay. Link to all the Carousel entries [so far 6 done, 4 left]

No worries. Take your time. But i have a request.  Would you mind sending the raw images somewhere? Extracting them from figma is a bit of pain.. Thanks :D

> also, should I merge this issue? or would you add the extra entries on this one?

This issue here is finished. So it is best that we close it and move on to the next one.

> , so feel free to move on to the next section.

This [branch](https://github.com/baseplate-admin/coreproject/tree/next-slide) is already being worked on :D

> Good day to you

Same to you

**Comment by AKindWorld** [comment]
> No worries. Take your time. But i have a request. Would you mind sending the raw images somewhere? Extracting them from figma is a bit of pain.. Thanks :D

Yup I have already given the links to the original HQ images in the Figma file itself. Just look below the slides for a link - it would redirect to the original image. I've adding those for myself too, since I'm no longer saving the poster files myself (would do it later since I need to reorganize my files a bit).

> This issue here is finished. So it is best that we close it and move on to the next one.

Alrighty then. Merging this!

Once again, great work!

^^

**Comment by baseplate-admin** [comment]
> Yup I have already given the links to the original HQ images in the Figma file itself. Just look below the slides for a link - it would redirect to the original image. I've adding those for myself too, since I'm no longer saving the poster files myself (would do it later since I need to reorganize my files a bit).

I completely missed the links. Sorry for bad ping ;"/

**Pull request merged**
